version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'

      open-pull-requests-limit: 10

      ignore:
          - dependency-name: 'node'
          - dependency-name: '@types/node'

      groups:
          fvtt-types:
              patterns:
                  - 'fvtt-types'

          other-dependencies-minor-and-patch:
              patterns:
                  - '*'
              exclude-patterns:
                  - 'fvtt-types'
              update-types: ['minor', 'patch']

          other-dependencies-major:
              patterns:
                  - '*'
              exclude-patterns:
                  - 'fvtt-types'
              update-types: ['major']

      labels:
          - 'dependencies'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      labels:
          - 'dependencies'
          - 'github-actions'
