version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'

      open-pull-requests-limit: 10

      groups:
          lint-and-format:
              patterns:
                  - 'oxlint'
                  - 'oxlint-tsgolint'
                  - 'prettier'
              update-types: ['minor', 'patch']

          build-tools:
              patterns:
                  - 'esbuild'
                  - 'fs-extra'
                  - 'gulp*'
                  - 'sass'
              update-types: ['minor', 'patch']

          tests-and-browser:
              patterns:
                  - '@ethaks/fvtt-quench'
                  - '@types/chai'
                  - '@types/mocha'
                  - 'playwright'
              update-types: ['minor', 'patch']

          foundry-tools:
              patterns:
                  - '@foundryvtt/*'
              update-types: ['minor', 'patch']

      labels:
          - 'dependencies'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      labels:
          - 'dependencies'
          - 'github-actions'
