export default {
    printWidth: 120,
    tabWidth: 4,
    useTabs: false,
    singleQuote: true,
    semi: true,
    quoteProps: 'as-needed',
    trailingComma: 'all',
    bracketSpacing: true,
    objectWrap: 'collapse',
    bracketSameLine: false,
    arrowParens: 'always',
    htmlWhitespaceSensitivity: 'css',
    endOfLine: 'lf',
    singleAttributePerLine: false,
    proseWrap: 'always',
};
