import { QuenchBatchContext } from '@ethaks/fvtt-quench';
import { MountedWeaponParser } from '../../module/apps/characterImport/vehicleImport/MountedWeaponParser';

export const mountedWeaponParserTesting = (context: QuenchBatchContext) => {
    const { describe, it, assert, before, after } = context;

    let chummerVehicle =        
        {
          "guid": "cb8dfbb8-33c1-437b-93b4-e1c19384e3ae",
          "sourceid": "e338dcf9-3149-4519-9228-589354be5667",
          "name": "Messerschmitt-Kawasaki Jagdschrecke",
          "name_english": "Messerschmitt-Kawasaki Jagdschrecke",
          "fullname": "Messerschmitt-Kawasaki Jagdschrecke",
          "category": "Große Drohnen",
          "category_english": "Drones: Large",
          "isdrone": "True",
          "handling": "5",
          "accel": "2",
          "speed": "4",
          "pilot": "3",
          "body": "6",
          "armor": "8",
          "seats": "0",
          "sensor": "3",
          "avail": "10V",
          "cost": "31.350",
          "owncost": "28.800",
          "source": "SAG",
          "page": "69",
          "physicalcm": "9",
          "physicalcmfilled": "0",
          "vehiclename": null,
          "maneuver": "0",
          "location": null,
          "attack": "0",
          "sleaze": "0",
          "dataprocessing": "3",
          "firewall": "3",
          "devicerating": "3",
          "programlimit": "3",
          "iscommlink": "False",
          "isprogram": "False",
          "active": "False",
          "homenode": "False",
          "matrixcm": "10",
          "matrixcmfilled": "0",
          "mods": {
            "mod": [
              {
                "guid": "3cde5586-094c-488e-8379-782a73c3998e",
                "sourceid": "518a5fdc-3b2c-42a6-a3fb-3cb88918fe72",
                "name": "ECM",
                "name_english": "ECM",
                "fullname": "ECM (Stufe 3)",
                "category": "Electromagnetic",
                "category_english": "Electromagnetic",
                "limit": null,
                "slots": "2",
                "rating": "3",
                "ratinglabel": "String_Rating",
                "avail": "9V",
                "cost": "1.500",
                "owncost": "1.500",
                "source": "R5",
                "wirelesson": "False",
                "page": "173",
                "included": "True",
                "weapons": null,
                "cyberwares": null
              },
              {
                "guid": "f66fa2cf-dd5c-4a6e-a425-93290fffd18c",
                "sourceid": "30099989-d8ca-4f9c-adf0-1de36b6f8ab6",
                "source": "R5",
                "name": "Riesig",
                "name_english": "Huge (Drone)",
                "fullname": "Riesig (Fest, Ferngesteuert, Extern)",
                "category": "Size",
                "category_english": "Size",
                "limit": null,
                "slots": "5",
                "avail": "16V",
                "cost": "1.950",
                "owncost": "3.000",
                "page": "132",
                "location": null,
                "included": "True",
                "weapons": {
                  "weapon": {
                    "guid": "119bc767-e10c-4816-82b5-fac94f2c4291",
                    "sourceid": "23141cfc-e7c9-4af9-b4e0-a7f0443f1170",
                    "name": "Shiawase Arms Monsoon",
                    "fullname": "Shiawase Arms Monsoon",
                    "name_english": "Shiawase Arms Monsoon",
                    "category": "Sturmgewehre",
                    "category_english": "Assault Rifles",
                    "type": "Ranged",
                    "reach": "0",
                    "accuracy": "5 (7)",
                    "accuracy_noammo": "5 (7)",
                    "rawaccuracy": "5",
                    "damage": "10K",
                    "damage_noammo": "10K",
                    "damage_english": "10P",
                    "damage_noammo_english": "10P",
                    "rawdamage": "10P",
                    "ap": "-1",
                    "ap_noammo": "-1",
                    "rawap": "-1",
                    "mode": "HM/AM",
                    "mode_noammo": "HM/AM",
                    "rc": "2",
                    "rc_noammo": "2",
                    "rawrc": "0",
                    "ammo": "20(v)",
                    "ammo_english": "20(ml)",
                    "maxammo": "20(ml)",
                    "conceal": "+6",
                    "avail": "10V",
                    "cost": "1.900",
                    "owncost": "1.900",
                    "weight": "0",
                    "ownweight": "0",
                    "source": "GH3",
                    "page": "13",
                    "weaponname": null,
                    "location": null,
                    "attack": "0",
                    "sleaze": "0",
                    "dataprocessing": "2",
                    "firewall": "2",
                    "devicerating": "2",
                    "programlimit": "0",
                    "iscommlink": "False",
                    "isprogram": "False",
                    "active": "False",
                    "homenode": "False",
                    "conditionmonitor": "9",
                    "matrixcmfilled": "0",
                    "accessories": {
                      "accessory": [
                        {
                          "guid": "ea8dde14-ef8a-4e7e-acc2-50f9478a353d",
                          "sourceid": "2da4f104-cf0c-4e0c-a001-4a6da4c2b46b",
                          "name": "Elektronisches Feuern",
                          "name_english": "Electronic Firing",
                          "mount": "Internal",
                          "extramount": "None",
                          "rc": "1",
                          "conceal": "0",
                          "avail": "10E",
                          "ratinglabel": "String_Rating",
                          "cost": "0",
                          "owncost": "0",
                          "weight": "0",
                          "ownweight": "0",
                          "included": "True",
                          "source": "HT",
                          "page": "172",
                          "accuracy": "0"
                        },
                        {
                          "guid": "bb716d62-cdfa-4f7d-9d20-02c6490d9779",
                          "sourceid": "d57d2c64-1f61-4f5f-a465-8ce0dfacec6a",
                          "name": "Smartgunsystem, intern",
                          "name_english": "Smartgun System, Internal",
                          "mount": "Internal",
                          "extramount": "None",
                          "rc": null,
                          "conceal": "0",
                          "avail": "+2E",
                          "ratinglabel": "String_Rating",
                          "cost": "0",
                          "owncost": "0",
                          "weight": "0",
                          "ownweight": "0",
                          "included": "True",
                          "source": "SR5",
                          "page": "435",
                          "accuracy": "+2",
                          "gears": {
                            "gear": [
                              {
                                "guid": "e17745b5-f978-4813-9116-fe93eda45142",
                                "sourceid": "3a79e046-8106-4089-a1ab-895eee956b86",
                                "name": "Laser-Entfernungsmesser",
                                "name_english": "Laser Range Finder",
                                "category": "Sensor-Funktionen",
                                "category_english": "Sensor Functions",
                                "ispersona": "False",
                                "isammo": "False",
                                "issin": "False",
                                "capacity": "[1]",
                                "armorcapacity": "[1]",
                                "maxrating": null,
                                "rating": "0",
                                "qty": "1",
                                "avail": "0",
                                "avail_english": "0",
                                "cost": "0",
                                "owncost": "1",
                                "weight": "0",
                                "ownweight": "0",
                                "extra": null,
                                "bonded": "False",
                                "equipped": "True",
                                "wirelesson": "False",
                                "location": null,
                                "gearname": null,
                                "source": "SR5",
                                "page": "450",
                                "attack": "0",
                                "sleaze": "0",
                                "dataprocessing": "0",
                                "firewall": "0",
                                "devicerating": "0",
                                "programlimit": "0",
                                "iscommlink": "False",
                                "isprogram": "False",
                                "active": "False",
                                "homenode": "False",
                                "conditionmonitor": "8",
                                "matrixcmfilled": "0",
                                "children": null,
                                "weaponbonusdamage": "+0",
                                "weaponbonusdamage_english": "+0",
                                "weaponbonusap": "+0",
                                "weaponbonusacc": "+0",
                                "weaponbonusrange": "0",
                                "flechetteweaponbonusdamage": "+0",
                                "flechetteweaponbonusdamage_english": "+0",
                                "flechetteweaponbonusap": "+0",
                                "flechetteweaponbonusacc": "+0",
                                "flechetteweaponbonusrange": "0"
                              },
                              {
                                "guid": "2d57ce71-de31-4a95-b751-4b37a5609bac",
                                "sourceid": "fa6fa434-107b-4f36-a138-f98b044dae76",
                                "name": "Mikrokamera",
                                "name_english": "Camera, Micro",
                                "category": "Sichtgeräte",
                                "category_english": "Vision Devices",
                                "ispersona": "False",
                                "isammo": "False",
                                "issin": "False",
                                "capacity": "1",
                                "armorcapacity": "[1]",
                                "maxrating": null,
                                "rating": "0",
                                "qty": "1",
                                "avail": "0",
                                "avail_english": "0",
                                "cost": "0",
                                "owncost": "1",
                                "weight": "0",
                                "ownweight": "0",
                                "extra": null,
                                "bonded": "False",
                                "equipped": "True",
                                "wirelesson": "False",
                                "location": null,
                                "gearname": null,
                                "source": "SR5",
                                "page": "447",
                                "attack": "0",
                                "sleaze": "0",
                                "dataprocessing": "0",
                                "firewall": "0",
                                "devicerating": "0",
                                "programlimit": "0",
                                "iscommlink": "False",
                                "isprogram": "False",
                                "active": "False",
                                "homenode": "False",
                                "conditionmonitor": "8",
                                "matrixcmfilled": "0",
                                "children": null,
                                "weaponbonusdamage": "+0",
                                "weaponbonusdamage_english": "+0",
                                "weaponbonusap": "+0",
                                "weaponbonusacc": "+0",
                                "weaponbonusrange": "0",
                                "flechetteweaponbonusdamage": "+0",
                                "flechetteweaponbonusdamage_english": "+0",
                                "flechetteweaponbonusap": "+0",
                                "flechetteweaponbonusacc": "+0",
                                "flechetteweaponbonusrange": "0"
                              }
                            ]
                          }
                        }
                      ]
                    },
                    "ranges": [
                      {
                        "name": "Sturmgewehre",
                        "short": "0-25",
                        "medium": "26-150",
                        "long": "151-350",
                        "extreme": "351-550"
                      },
                      {
                        "name": "Sturmgewehre",
                        "short": "0-25",
                        "medium": "26-150",
                        "long": "151-350",
                        "extreme": "351-550"
                      }
                    ],
                    "alternateranges": [
                      {
                        "name": null,
                        "short": null,
                        "medium": null,
                        "long": null,
                        "extreme": null
                      },
                      {
                        "name": null,
                        "short": null,
                        "medium": null,
                        "long": null,
                        "extreme": null
                      }
                    ],
                    "availableammo": "60",
                    "currentammo": "-",
                    "clips": null,
                    "dicepool": "14",
                    "dicepool_noammo": "14",
                    "skill": "Automatics",
                    "wirelesson": "True"
                  }
                },
                "mods": {
                  "mod": {
                    "guid": "657a930c-8a11-4843-96f1-822090ec6cc3",
                    "sourceid": "c3f9f5a4-b8d4-11e6-80f5-76304dec7eb7",
                    "name": "Größerer Munitionsvorrat (Zweiter Behälter)",
                    "name_english": "Expanded Ammunition Bay (Second Bin) Weapon Mount Add-on (Drone)",
                    "fullname": "Größerer Munitionsvorrat (Zweiter Behälter)",
                    "category": "All",
                    "category_english": "All",
                    "limit": null,
                    "slots": "1",
                    "rating": "0",
                    "ratinglabel": "String_Rating",
                    "avail": "0",
                    "cost": "50",
                    "owncost": "50",
                    "source": "R5",
                    "wirelesson": "False",
                    "page": "132",
                    "included": "True",
                    "weapons": null,
                    "cyberwares": null
                  }
                }
              }
            ]
          },
          "gears": {
            "gear": [
              {
                "guid": "70d28c3e-8689-4d52-8cd1-6d3b66278d6e",
                "sourceid": "2ca81a10-d0f7-4b39-ac93-a84f2f69f9d9",
                "name": "Sensorarray",
                "name_english": "Sensor Array",
                "category": "Sensorpakete",
                "category_english": "Sensors",
                "ispersona": "False",
                "isammo": "False",
                "issin": "False",
                "capacity": "8/[0]",
                "armorcapacity": "[0]",
                "maxrating": "8",
                "rating": "3",
                "qty": "1",
                "avail": "7",
                "avail_english": "7",
                "cost": "0",
                "owncost": "1",
                "weight": "0",
                "ownweight": "0",
                "extra": null,
                "bonded": "False",
                "equipped": "True",
                "wirelesson": "False",
                "location": null,
                "gearname": null,
                "source": "SR5",
                "page": "445",
                "attack": "0",
                "sleaze": "0",
                "dataprocessing": "0",
                "firewall": "0",
                "devicerating": "0",
                "programlimit": "0",
                "iscommlink": "False",
                "isprogram": "False",
                "active": "False",
                "homenode": "False",
                "conditionmonitor": "8",
                "matrixcmfilled": "0",
                "children": {
                  "gear": [
                    {
                      "guid": "c1c7a346-954c-4de7-8236-746337a22632",
                      "sourceid": "07805498-75ea-441f-bd27-6536d4131b51",
                      "name": "Kamera",
                      "name_english": "Camera",
                      "category": "Sensor-Funktionen",
                      "category_english": "Sensor Functions",
                      "ispersona": "False",
                      "isammo": "False",
                      "issin": "False",
                      "capacity": "Rating/[1]",
                      "armorcapacity": "Rating/[1]",
                      "maxrating": "{Parent Rating}",
                      "rating": "3",
                      "qty": "1",
                      "avail": "0",
                      "avail_english": "0",
                      "cost": "0",
                      "owncost": "0",
                      "weight": "0",
                      "ownweight": "0",
                      "extra": null,
                      "bonded": "False",
                      "equipped": "True",
                      "wirelesson": "False",
                      "location": null,
                      "gearname": null,
                      "source": "SR5",
                      "page": "447",
                      "attack": "0",
                      "sleaze": "0",
                      "dataprocessing": "0",
                      "firewall": "0",
                      "devicerating": "0",
                      "programlimit": "0",
                      "iscommlink": "False",
                      "isprogram": "False",
                      "active": "False",
                      "homenode": "False",
                      "conditionmonitor": "8",
                      "matrixcmfilled": "0",
                      "children": null,
                      "weaponbonusdamage": "+0",
                      "weaponbonusdamage_english": "+0",
                      "weaponbonusap": "+0",
                      "weaponbonusacc": "+0",
                      "weaponbonusrange": "0",
                      "flechetteweaponbonusdamage": "+0",
                      "flechetteweaponbonusdamage_english": "+0",
                      "flechetteweaponbonusap": "+0",
                      "flechetteweaponbonusacc": "+0",
                      "flechetteweaponbonusrange": "0"
                    },
                    {
                      "guid": "ae6226c6-3f66-402e-8a01-f7029f7b5492",
                      "sourceid": "adf3533a-461c-46ae-9ee7-77dfd31c5d5a",
                      "name": "Sichtvergrößerung",
                      "name_english": "Vision Magnification",
                      "category": "Sensor-Funktionen",
                      "category_english": "Sensor Functions",
                      "ispersona": "False",
                      "isammo": "False",
                      "issin": "False",
                      "capacity": "[1]",
                      "armorcapacity": "[1]",
                      "maxrating": null,
                      "rating": "0",
                      "qty": "1",
                      "avail": "0",
                      "avail_english": "0",
                      "cost": "0",
                      "owncost": "0",
                      "weight": "0",
                      "ownweight": "0",
                      "extra": null,
                      "bonded": "False",
                      "equipped": "True",
                      "wirelesson": "False",
                      "location": null,
                      "gearname": null,
                      "source": "SR5",
                      "page": "458",
                      "attack": "0",
                      "sleaze": "0",
                      "dataprocessing": "0",
                      "firewall": "0",
                      "devicerating": "0",
                      "programlimit": "0",
                      "iscommlink": "False",
                      "isprogram": "False",
                      "active": "False",
                      "homenode": "False",
                      "conditionmonitor": "8",
                      "matrixcmfilled": "0",
                      "children": null,
                      "weaponbonusdamage": "+0",
                      "weaponbonusdamage_english": "+0",
                      "weaponbonusap": "+0",
                      "weaponbonusacc": "+0",
                      "weaponbonusrange": "0",
                      "flechetteweaponbonusdamage": "+0",
                      "flechetteweaponbonusdamage_english": "+0",
                      "flechetteweaponbonusap": "+0",
                      "flechetteweaponbonusacc": "+0",
                      "flechetteweaponbonusrange": "0"
                    },
                    {
                      "guid": "43e69eb8-cc8d-4aa5-9106-bc22ff0a44d5",
                      "sourceid": "e853967a-a2b8-4d89-9a97-773034489a16",
                      "name": "Bewegungsmelder",
                      "name_english": "Motion Sensor",
                      "category": "Sensor-Funktionen",
                      "category_english": "Sensor Functions",
                      "ispersona": "False",
                      "isammo": "False",
                      "issin": "False",
                      "capacity": "[1]",
                      "armorcapacity": "[1]",
                      "maxrating": null,
                      "rating": "0",
                      "qty": "1",
                      "avail": "0",
                      "avail_english": "0",
                      "cost": "0",
                      "owncost": "0",
                      "weight": "0",
                      "ownweight": "0",
                      "extra": null,
                      "bonded": "False",
                      "equipped": "True",
                      "wirelesson": "False",
                      "location": null,
                      "gearname": null,
                      "source": "SR5",
                      "page": "450",
                      "attack": "0",
                      "sleaze": "0",
                      "dataprocessing": "0",
                      "firewall": "0",
                      "devicerating": "0",
                      "programlimit": "0",
                      "iscommlink": "False",
                      "isprogram": "False",
                      "active": "False",
                      "homenode": "False",
                      "conditionmonitor": "8",
                      "matrixcmfilled": "0",
                      "children": null,
                      "weaponbonusdamage": "+0",
                      "weaponbonusdamage_english": "+0",
                      "weaponbonusap": "+0",
                      "weaponbonusacc": "+0",
                      "weaponbonusrange": "0",
                      "flechetteweaponbonusdamage": "+0",
                      "flechetteweaponbonusdamage_english": "+0",
                      "flechetteweaponbonusap": "+0",
                      "flechetteweaponbonusacc": "+0",
                      "flechetteweaponbonusrange": "0"
                    },
                    {
                      "guid": "fb91dcb9-22bf-48ac-a88f-77a2bdb0a42a",
                      "sourceid": "4d12e4a1-edd3-4abf-830f-aa95874b7531",
                      "name": "Radiosignalscanner",
                      "name_english": "Radio Signal Scanner",
                      "category": "Sensor-Funktionen",
                      "category_english": "Sensor Functions",
                      "ispersona": "False",
                      "isammo": "False",
                      "issin": "False",
                      "capacity": "[1]",
                      "armorcapacity": "[1]",
                      "maxrating": null,
                      "rating": "0",
                      "qty": "1",
                      "avail": "0",
                      "avail_english": "0",
                      "cost": "0",
                      "owncost": "0",
                      "weight": "0",
                      "ownweight": "0",
                      "extra": null,
                      "bonded": "False",
                      "equipped": "True",
                      "wirelesson": "False",
                      "location": null,
                      "gearname": null,
                      "source": "SR5",
                      "page": "450",
                      "attack": "0",
                      "sleaze": "0",
                      "dataprocessing": "0",
                      "firewall": "0",
                      "devicerating": "0",
                      "programlimit": "0",
                      "iscommlink": "False",
                      "isprogram": "False",
                      "active": "False",
                      "homenode": "False",
                      "conditionmonitor": "8",
                      "matrixcmfilled": "0",
                      "children": null,
                      "weaponbonusdamage": "+0",
                      "weaponbonusdamage_english": "+0",
                      "weaponbonusap": "+0",
                      "weaponbonusacc": "+0",
                      "weaponbonusrange": "0",
                      "flechetteweaponbonusdamage": "+0",
                      "flechetteweaponbonusdamage_english": "+0",
                      "flechetteweaponbonusap": "+0",
                      "flechetteweaponbonusacc": "+0",
                      "flechetteweaponbonusrange": "0"
                    },
                    {
                      "guid": "77b66521-9295-4662-b3b6-cfafb4cb0abd",
                      "sourceid": "f25e4819-209c-4cbf-b24f-668359a7a2ad",
                      "name": "Lasermikrofon",
                      "name_english": "Laser Microphone",
                      "category": "Sensor-Funktionen",
                      "category_english": "Sensor Functions",
                      "ispersona": "False",
                      "isammo": "False",
                      "issin": "False",
                      "capacity": "Rating/[1]",
                      "armorcapacity": "Rating/[1]",
                      "maxrating": "{Parent Rating}",
                      "rating": "3",
                      "qty": "1",
                      "avail": "0",
                      "avail_english": "0",
                      "cost": "0",
                      "owncost": "0",
                      "weight": "0",
                      "ownweight": "0",
                      "extra": null,
                      "bonded": "False",
                      "equipped": "True",
                      "wirelesson": "False",
                      "location": null,
                      "gearname": null,
                      "source": "SR5",
                      "page": "449",
                      "attack": "0",
                      "sleaze": "0",
                      "dataprocessing": "0",
                      "firewall": "0",
                      "devicerating": "0",
                      "programlimit": "0",
                      "iscommlink": "False",
                      "isprogram": "False",
                      "active": "False",
                      "homenode": "False",
                      "conditionmonitor": "8",
                      "matrixcmfilled": "0",
                      "children": null,
                      "weaponbonusdamage": "+0",
                      "weaponbonusdamage_english": "+0",
                      "weaponbonusap": "+0",
                      "weaponbonusacc": "+0",
                      "weaponbonusrange": "0",
                      "flechetteweaponbonusdamage": "+0",
                      "flechetteweaponbonusdamage_english": "+0",
                      "flechetteweaponbonusap": "+0",
                      "flechetteweaponbonusacc": "+0",
                      "flechetteweaponbonusrange": "0"
                    },
                    {
                      "guid": "9ba219c5-cb2a-4d0d-85fa-9e11b023f14c",
                      "sourceid": "d98f419f-7625-4228-9723-0217950d8155",
                      "name": "Geigerzähler",
                      "name_english": "Geiger Counter",
                      "category": "Sensor-Funktionen",
                      "category_english": "Sensor Functions",
                      "ispersona": "False",
                      "isammo": "False",
                      "issin": "False",
                      "capacity": "[1]",
                      "armorcapacity": "[1]",
                      "maxrating": null,
                      "rating": "0",
                      "qty": "1",
                      "avail": "0",
                      "avail_english": "0",
                      "cost": "0",
                      "owncost": "0",
                      "weight": "0",
                      "ownweight": "0",
                      "extra": null,
                      "bonded": "False",
                      "equipped": "True",
                      "wirelesson": "False",
                      "location": null,
                      "gearname": null,
                      "source": "SR5",
                      "page": "450",
                      "attack": "0",
                      "sleaze": "0",
                      "dataprocessing": "0",
                      "firewall": "0",
                      "devicerating": "0",
                      "programlimit": "0",
                      "iscommlink": "False",
                      "isprogram": "False",
                      "active": "False",
                      "homenode": "False",
                      "conditionmonitor": "8",
                      "matrixcmfilled": "0",
                      "children": null,
                      "weaponbonusdamage": "+0",
                      "weaponbonusdamage_english": "+0",
                      "weaponbonusap": "+0",
                      "weaponbonusacc": "+0",
                      "weaponbonusrange": "0",
                      "flechetteweaponbonusdamage": "+0",
                      "flechetteweaponbonusdamage_english": "+0",
                      "flechetteweaponbonusap": "+0",
                      "flechetteweaponbonusacc": "+0",
                      "flechetteweaponbonusrange": "0"
                    }
                  ]
                },
                "weaponbonusdamage": "+0",
                "weaponbonusdamage_english": "+0",
                "weaponbonusap": "+0",
                "weaponbonusacc": "+0",
                "weaponbonusrange": "0",
                "flechetteweaponbonusdamage": "+0",
                "flechetteweaponbonusdamage_english": "+0",
                "flechetteweaponbonusap": "+0",
                "flechetteweaponbonusacc": "+0",
                "flechetteweaponbonusrange": "0"
              },
              {
                "guid": "156b06ee-654b-4224-91a8-f459f4ef7037",
                "sourceid": "0949997a-acb7-49d9-9905-5ae2cd35626f",
                "name": "Zielerfassung [Waffe] Autosoft",
                "name_english": "[Weapon] Targeting Autosoft",
                "category": "Autosofts",
                "category_english": "Autosofts",
                "ispersona": "False",
                "isammo": "False",
                "issin": "False",
                "capacity": "[0]",
                "armorcapacity": "[0]",
                "maxrating": "6",
                "rating": "4",
                "qty": "1",
                "avail": "8",
                "avail_english": "8",
                "cost": "0",
                "owncost": "1",
                "weight": "0",
                "ownweight": "0",
                "extra": "Shiawase Arms Monsoon",
                "bonded": "False",
                "equipped": "True",
                "wirelesson": "False",
                "location": null,
                "gearname": null,
                "source": "SR5",
                "page": "267",
                "attack": "0",
                "sleaze": "0",
                "dataprocessing": "0",
                "firewall": "0",
                "devicerating": "0",
                "programlimit": "0",
                "iscommlink": "False",
                "isprogram": "True",
                "active": "False",
                "homenode": "False",
                "conditionmonitor": "8",
                "matrixcmfilled": "0",
                "children": null,
                "weaponbonusdamage": "+0",
                "weaponbonusdamage_english": "+0",
                "weaponbonusap": "+0",
                "weaponbonusacc": "+0",
                "weaponbonusrange": "0",
                "flechetteweaponbonusdamage": "+0",
                "flechetteweaponbonusdamage_english": "+0",
                "flechetteweaponbonusap": "+0",
                "flechetteweaponbonusacc": "+0",
                "flechetteweaponbonusrange": "0"
              },
              {
                "guid": "1bfc2ff5-2c1b-4b7e-8abf-4ae2d9b30af8",
                "sourceid": "149a8dd2-dfef-473f-94a4-1bdd77e4f855",
                "name": "Clearsight Autosoft",
                "name_english": "Clearsight Autosoft",
                "category": "Autosofts",
                "category_english": "Autosofts",
                "ispersona": "False",
                "isammo": "False",
                "issin": "False",
                "capacity": "[0]",
                "armorcapacity": "[0]",
                "maxrating": "6",
                "rating": "4",
                "qty": "1",
                "avail": "8",
                "avail_english": "8",
                "cost": "0",
                "owncost": "1",
                "weight": "0",
                "ownweight": "0",
                "extra": null,
                "bonded": "False",
                "equipped": "True",
                "wirelesson": "False",
                "location": null,
                "gearname": null,
                "source": "SR5",
                "page": "267",
                "attack": "0",
                "sleaze": "0",
                "dataprocessing": "0",
                "firewall": "0",
                "devicerating": "0",
                "programlimit": "0",
                "iscommlink": "False",
                "isprogram": "True",
                "active": "False",
                "homenode": "False",
                "conditionmonitor": "8",
                "matrixcmfilled": "0",
                "children": null,
                "weaponbonusdamage": "+0",
                "weaponbonusdamage_english": "+0",
                "weaponbonusap": "+0",
                "weaponbonusacc": "+0",
                "weaponbonusrange": "0",
                "flechetteweaponbonusdamage": "+0",
                "flechetteweaponbonusdamage_english": "+0",
                "flechetteweaponbonusap": "+0",
                "flechetteweaponbonusacc": "+0",
                "flechetteweaponbonusrange": "0"
              },
              {
                "guid": "625dfbaf-0bb3-409e-b895-29e73aa683b9",
                "sourceid": "ef9c8aae-26df-4fe6-88b3-79fbb5eb77c5",
                "name": "Munition: APDS",
                "name_english": "Ammo: APDS",
                "category": "Munition",
                "category_english": "Ammunition",
                "ispersona": "False",
                "isammo": "True",
                "issin": "False",
                "capacity": null,
                "armorcapacity": null,
                "maxrating": null,
                "rating": "0",
                "qty": "30",
                "avail": "12V",
                "avail_english": "12F",
                "cost": "360",
                "owncost": "0,1",
                "weight": "0",
                "ownweight": "0",
                "extra": "Sturmgewehre",
                "bonded": "False",
                "equipped": "True",
                "wirelesson": "False",
                "location": null,
                "gearname": null,
                "source": "SR5",
                "page": "436",
                "attack": "0",
                "sleaze": "0",
                "dataprocessing": "0",
                "firewall": "0",
                "devicerating": "0",
                "programlimit": "0",
                "iscommlink": "False",
                "isprogram": "False",
                "active": "False",
                "homenode": "False",
                "conditionmonitor": "8",
                "matrixcmfilled": "0",
                "children": null,
                "weaponbonusdamage": "+0",
                "weaponbonusdamage_english": "+0",
                "weaponbonusap": "-4",
                "weaponbonusacc": "+0",
                "weaponbonusrange": "0",
                "flechetteweaponbonusdamage": "+0",
                "flechetteweaponbonusdamage_english": "+0",
                "flechetteweaponbonusap": "+0",
                "flechetteweaponbonusacc": "+0",
                "flechetteweaponbonusrange": "0"
              },
              {
                "guid": "efc5b9a0-7744-456e-ad52-bfd6f5a8cf45",
                "sourceid": "d9f69780-93eb-41ff-9a9c-893f8c52794e",
                "name": "Munition: Schocker",
                "name_english": "Ammo: Stick-n-Shock",
                "category": "Munition",
                "category_english": "Ammunition",
                "ispersona": "False",
                "isammo": "True",
                "issin": "False",
                "capacity": null,
                "armorcapacity": null,
                "maxrating": null,
                "rating": "0",
                "qty": "30",
                "avail": "6E",
                "avail_english": "6R",
                "cost": "240",
                "owncost": "0,1",
                "weight": "0",
                "ownweight": "0",
                "extra": "Assault Rifles",
                "bonded": "False",
                "equipped": "True",
                "wirelesson": "False",
                "location": null,
                "gearname": null,
                "source": "SR5",
                "page": "437",
                "attack": "0",
                "sleaze": "0",
                "dataprocessing": "0",
                "firewall": "0",
                "devicerating": "0",
                "programlimit": "0",
                "iscommlink": "False",
                "isprogram": "False",
                "active": "False",
                "homenode": "False",
                "conditionmonitor": "8",
                "matrixcmfilled": "0",
                "children": null,
                "weaponbonusdamage": "-2G(e)",
                "weaponbonusdamage_english": "-2S(e)",
                "weaponbonusap": "-5",
                "weaponbonusacc": "+0",
                "weaponbonusrange": "0",
                "flechetteweaponbonusdamage": "+0",
                "flechetteweaponbonusdamage_english": "+0",
                "flechetteweaponbonusap": "+0",
                "flechetteweaponbonusacc": "+0",
                "flechetteweaponbonusrange": "0"
              },
              {
                "guid": "e4d2d1cc-dbfa-4990-aa50-ed6a8eaab291",
                "sourceid": "0025f1c7-45a4-4ec5-a692-e18aab2f97a9",
                "name": "Transportsitz (Halterung)",
                "name_english": "Transportsitz (Halterung)",
                "category": "Eigene",
                "category_english": "Custom",
                "ispersona": "False",
                "isammo": "False",
                "issin": "False",
                "capacity": null,
                "armorcapacity": null,
                "maxrating": null,
                "rating": "0",
                "qty": "1",
                "avail": "0",
                "avail_english": "0",
                "cost": "0",
                "owncost": "1",
                "weight": "0",
                "ownweight": "0",
                "extra": null,
                "bonded": "False",
                "equipped": "True",
                "wirelesson": "False",
                "location": null,
                "gearname": null,
                "source": "SR5",
                "page": "1",
                "attack": "0",
                "sleaze": "0",
                "dataprocessing": "0",
                "firewall": "0",
                "devicerating": "0",
                "programlimit": "0",
                "iscommlink": "False",
                "isprogram": "False",
                "active": "False",
                "homenode": "False",
                "conditionmonitor": "8",
                "matrixcmfilled": "0",
                "children": null,
                "weaponbonusdamage": "+0",
                "weaponbonusdamage_english": "+0",
                "weaponbonusap": "+0",
                "weaponbonusacc": "+0",
                "weaponbonusrange": "0",
                "flechetteweaponbonusdamage": "+0",
                "flechetteweaponbonusdamage_english": "+0",
                "flechetteweaponbonusap": "+0",
                "flechetteweaponbonusacc": "+0",
                "flechetteweaponbonusrange": "0"
              }
            ]
          },
          "weapons": null
        }
    
    let mountedWeaponParser = new MountedWeaponParser()

    describe("Mounted Weapon Parser", () => {

      it("parses weapons", async () => {
          let weapons = await mountedWeaponParser.parseWeapons(chummerVehicle)
        
          assert.lengthOf(weapons, 1); 
      });

    })
}

