import { ActorFile } from "@/module/apps/actorImport/ActorSchema";

export const CompanionSprite = {
  "?xml": {
    "@version": "1.0",
    "@encoding": "utf-8"
  },
  "characters": {
    "character": {
      "settings": "67e25032-2a4e-42ca-97fa-69f7f608236c",
      "buildmethod": "Priority",
      "imageformat": "jpeg",
      "metatype": "Companion Sprite",
      "metatype_english": "Companion Sprite",
      "metatype_guid": "0b1c6eeb-682f-4f71-bc61-81b5c9c47241",
      "metavariant": null,
      "metavariant_english": null,
      "metavariant_guid": "00000000-0000-0000-0000-000000000000",
      "movement": "Special, Swim: Special, Fly: Special",
      "walk": "Special, Swim: Special, Fly: Special",
      "run": "Special, Swim: Special, Fly: Special",
      "sprint": "Special, Swim: Special, Fly: Special",
      "movementwalk": "Special",
      "movementswim": "Special",
      "movementfly": "Special",
      "prioritymetatype": "A",
      "priorityattributes": "B",
      "priorityspecial": "C",
      "priorityskills": [
        "D",
        null
      ],
      "priorityresources": "E",
      "primaryarm": "Right",
      "name": "Unnamed Character",
      "gender": null,
      "age": null,
      "eyes": null,
      "height": null,
      "weight": null,
      "skin": null,
      "hair": null,
      "description": null,
      "background": null,
      "concept": null,
      "notes": null,
      "alias": null,
      "playername": null,
      "gamenotes": null,
      "limitphysical": "0",
      "limitmental": "6",
      "limitsocial": "4",
      "limitastral": "6",
      "contactpoints": "6",
      "contactpointsused": "0",
      "cfplimit": "0",
      "ainormalprogramlimit": "0",
      "aiadvancedprogramlimit": "0",
      "spelllimit": "0",
      "karma": "0",
      "totalkarma": "0",
      "special": "0",
      "totalspecial": "0",
      "attributes": [
        "0",
        {
          "attributecategory_english": "Standard",
          "attribute": [
            {
              "name_english": "STR",
              "name": "STR",
              "base": "0",
              "total": "0",
              "min": "0",
              "max": "0",
              "aug": "0",
              "bp": "0",
              "metatypecategory": "Standard"
            },
            {
              "name_english": "CHA",
              "name": "CHA",
              "base": "2",
              "total": "2",
              "min": "2",
              "max": "2",
              "aug": "2",
              "bp": "0",
              "metatypecategory": "Standard"
            },
            {
              "name_english": "INT",
              "name": "INT",
              "base": "4",
              "total": "4",
              "min": "4",
              "max": "4",
              "aug": "4",
              "bp": "0",
              "metatypecategory": "Standard"
            },
            {
              "name_english": "AGI",
              "name": "AGI",
              "base": "0",
              "total": "0",
              "min": "0",
              "max": "0",
              "aug": "0",
              "bp": "0",
              "metatypecategory": "Standard"
            },
            {
              "name_english": "REA",
              "name": "REA",
              "base": "0",
              "total": "0",
              "min": "0",
              "max": "0",
              "aug": "0",
              "bp": "0",
              "metatypecategory": "Standard"
            },
            {
              "name_english": "ESS",
              "name": "ESS",
              "base": "1",
              "total": "1",
              "min": "1",
              "max": "1",
              "aug": "1",
              "bp": "0",
              "metatypecategory": "Special"
            },
            {
              "name_english": "EDG",
              "name": "EDG",
              "base": "1",
              "total": "1",
              "min": "1",
              "max": "1",
              "aug": "1",
              "bp": "0",
              "metatypecategory": "Special"
            },
            {
              "name_english": "LOG",
              "name": "LOG",
              "base": "3",
              "total": "3",
              "min": "3",
              "max": "3",
              "aug": "3",
              "bp": "0",
              "metatypecategory": "Standard"
            },
            {
              "name_english": "BOD",
              "name": "BOD",
              "base": "0",
              "total": "0",
              "min": "0",
              "max": "0",
              "aug": "0",
              "bp": "0",
              "metatypecategory": "Standard"
            },
            {
              "name_english": "WIL",
              "name": "WIL",
              "base": "7",
              "total": "7",
              "min": "7",
              "max": "7",
              "aug": "7",
              "bp": "0",
              "metatypecategory": "Standard"
            }
          ]
        }
      ],
      "totalattributes": "0",
      "edgeused": "0",
      "edgeremaining": "1",
      "streetcred": "0",
      "calculatedstreetcred": "0",
      "totalstreetcred": "0",
      "burntstreetcred": "0",
      "notoriety": "0",
      "calculatednotoriety": "0",
      "totalnotoriety": "0",
      "publicawareness": "0",
      "calculatedpublicawareness": "0",
      "totalpublicawareness": "0",
      "astralreputation": "0",
      "totalastralreputation": "0",
      "wildreputation": "0",
      "totalwildreputation": "0",
      "created": "True",
      "nuyen": "0",
      "adept": "False",
      "magician": "False",
      "technomancer": "True",
      "ai": "False",
      "cyberwaredisabled": "False",
      "critter": "True",
      "totaless": "1.00",
      "dodge": "4",
      "armor": "0",
      "firearmor": "0",
      "coldarmor": "0",
      "electricityarmor": "0",
      "acidarmor": "0",
      "fallingarmor": "0",
      "armordicestun": "0",
      "firearmordicestun": "0",
      "coldarmordicestun": "0",
      "electricityarmordicestun": "0",
      "acidarmordicestun": "0",
      "fallingarmordicestun": "0",
      "armordicephysical": "0",
      "firearmordicephysical": "0",
      "coldarmordicephysical": "0",
      "electricityarmordicephysical": "0",
      "acidarmordicephysical": "0",
      "fallingarmordicephysical": "0",
      "physicalcm": "8",
      "physicalcmiscorecm": "False",
      "stuncm": "12",
      "stuncmismatrixcm": "False",
      "physicalcmfilled": "0",
      "stuncmfilled": "0",
      "cmthreshold": "3",
      "physicalcmthresholdoffset": "0",
      "stuncmthresholdoffset": "0",
      "cmoverflow": "1",
      "psyche": "False",
      "init": "4 + 1d6",
      "initdice": "1",
      "initvalue": "4",
      "initbonus": "0",
      "matrixarinit": "4 + 1d6",
      "matrixarinitdice": "1",
      "matrixarinitvalue": "4",
      "matrixcoldinit": "4 + DP + 3d6",
      "matrixcoldinitdice": "3",
      "matrixcoldinitvalue": "4",
      "matrixhotinit": "4 + DP + 4d6",
      "matrixhotinitdice": "4",
      "matrixhotinitvalue": "4",
      "riggerinit": "4 + 1d6",
      "magenabled": "False",
      "initiategrade": "0",
      "resenabled": "False",
      "submersiongrade": "0",
      "depenabled": "False",
      "groupmember": "False",
      "groupname": null,
      "groupnotes": null,
      "surprise": "4",
      "composure": "9",
      "judgeintentions": "6",
      "judgeintentionsresist": "9",
      "liftandcarry": "0",
      "memory": "10",
      "liftweight": "0",
      "carryweight": "0",
      "totalcarriedweight": "0",
      "fatigueresist": "7",
      "radiationresist": "7",
      "sonicresist": "7",
      "toxincontactresist": "7",
      "toxiningestionresist": "7",
      "toxininhalationresist": "7",
      "toxininjectionresist": "7",
      "pathogencontactresist": "7",
      "pathogeningestionresist": "7",
      "pathogeninhalationresist": "7",
      "pathogeninjectionresist": "7",
      "physiologicaladdictionresistfirsttime": "7",
      "physiologicaladdictionresistalreadyaddicted": "7",
      "psychologicaladdictionresistfirsttime": "10",
      "psychologicaladdictionresistalreadyaddicted": "10",
      "physicalcmnaturalrecovery": "0",
      "stuncmnaturalrecovery": "7",
      "indirectdefenseresist": "4",
      "directmanaresist": "7",
      "directphysicalresist": "0",
      "detectionspellresist": "10",
      "decreasebodresist": "7",
      "decreaseagiresist": "7",
      "decreaserearesist": "7",
      "decreasestrresist": "7",
      "decreasecharesist": "9",
      "decreaseintresist": "11",
      "decreaselogresist": "10",
      "decreasewilresist": "14",
      "illusionmanaresist": "10",
      "illusionphysicalresist": "7",
      "manipulationmentalresist": "10",
      "manipulationphysicalresist": "0",
      "skills": {
        "skill": [
          {
            "guid": "cd740fa7-f744-4264-90f6-ab9b71580657",
            "suid": "b52f7575-eebf-41c4-938d-df3397b5ee68",
            "name": "Aeronautics Mechanic",
            "name_english": "Aeronautics Mechanic",
            "skillgroup": "Engineering",
            "skillgroup_english": "Engineering",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "143",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "7bb6ef0e-46d2-4f55-808e-1e68d06130db",
            "suid": "e09e5aa7-e496-41a2-97ce-17f577361888",
            "name": "Animal Handling",
            "name_english": "Animal Handling",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "143",
            "attributemod": "2",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "d2ae7a1c-2491-4cc0-b0fd-91804a9877a4",
            "suid": "74a68a9e-8c5b-4998-8dbb-08c1e768afc3",
            "name": "Arcana",
            "name_english": "Arcana",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Pseudo-Magical Active",
            "skillcategory_english": "Pseudo-Magical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "142",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "f590b45e-884d-4fa0-b2b8-20ff6634c3c3",
            "suid": "1537ca5c-fa93-4c05-b073-a2a0eed91b8e",
            "name": "Archery",
            "name_english": "Archery",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "130",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "cf1bd3cd-ed98-48a5-b348-30cdd363b6aa",
            "suid": "ada6d9b2-e451-4289-be45-7085fa34a51a",
            "name": "Armorer",
            "name_english": "Armorer",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "143",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "b2ef03c3-9426-4e91-9d35-ad3e416053c6",
            "suid": "2f4c706f-5ac5-4774-8a45-3b4667989a20",
            "name": "Artisan",
            "name_english": "Artisan",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "INT",
            "displayattribute": "INT",
            "source": "SR5",
            "page": "143",
            "attributemod": "4",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "2bee889a-90bf-443a-a877-55f7fc80b6b3",
            "suid": "788b387b-ee41-4e6a-bf22-481a8cc4cf9f",
            "name": "Automatics",
            "name_english": "Automatics",
            "skillgroup": "Firearms",
            "skillgroup_english": "Firearms",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "130",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "ea1ae3e9-9f12-4c0a-9aeb-df0a9a722944",
            "suid": "5e5f2f7f-f63b-4f65-a65d-91b3d4523c6f",
            "name": "Automotive Mechanic",
            "name_english": "Automotive Mechanic",
            "skillgroup": "Engineering",
            "skillgroup_english": "Engineering",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "143",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "2acb752f-e837-4354-aa1e-67604e289e87",
            "suid": "ba624682-a5c0-4cf5-b47b-1021e6a1800d",
            "name": "Biotechnology",
            "name_english": "Biotechnology",
            "skillgroup": "Biotech",
            "skillgroup_english": "Biotech",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "e3b271cb-8f1c-45cf-aeaf-75aa8a647ae4",
            "suid": "48763fa5-4b89-48c7-80ff-d0a2761de4c0",
            "name": "Blades",
            "name_english": "Blades",
            "skillgroup": "Close Combat",
            "skillgroup_english": "Close Combat",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "130",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "431b3acd-c99f-47d4-9a6f-04933da306a1",
            "suid": "bd4d977a-cbd4-4289-99bb-896caed6786a",
            "name": "Chemistry",
            "name_english": "Chemistry",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "63cd7378-f302-4816-aba5-ac8c1cf354ba",
            "suid": "cd9f6bf7-fa48-464b-9a8f-c7ce26713a72",
            "name": "Clubs",
            "name_english": "Clubs",
            "skillgroup": "Close Combat",
            "skillgroup_english": "Close Combat",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "131",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "7309315d-d55a-4849-a7de-c579ad5da962",
            "suid": "1c14bf0d-cc69-4126-9a95-1f2429c11aa5",
            "name": "Computer",
            "name_english": "Computer",
            "skillgroup": "Electronics",
            "skillgroup_english": "Electronics",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "3",
            "ratingmax": "12",
            "specializedrating": "6",
            "total": "6",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "3",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "9659d10e-04c8-4b1c-9ddd-7ac7dd1f0b6a",
            "suid": "6d7f48d3-84a1-4fce-90d3-58d566f70fa6",
            "name": "Con",
            "name_english": "Con",
            "skillgroup": "Acting",
            "skillgroup_english": "Acting",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "138",
            "attributemod": "2",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "d6c932a9-92d7-4061-8ed1-5e8926685b92",
            "suid": "7143f979-aa48-4cc8-a29c-e010400e6e11",
            "name": "Cybercombat",
            "name_english": "Cybercombat",
            "skillgroup": "Cracking",
            "skillgroup_english": "Cracking",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "0742ac80-72de-47e1-a3f0-f63445b70735",
            "suid": "9b386fe5-83b3-436f-9035-efd1c0f7a680",
            "name": "Cybertechnology",
            "name_english": "Cybertechnology",
            "skillgroup": "Biotech",
            "skillgroup_english": "Biotech",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "3e4bd8b8-27ee-4060-9218-11633350e27a",
            "suid": "276877e1-5cdf-4e95-befd-13c1abb5ae02",
            "name": "Demolitions",
            "name_english": "Demolitions",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "50177b8a-6bda-4007-be5e-f7567c411f59",
            "suid": "9b2416b2-3e2b-4dd6-ab9d-530f493c1c22",
            "name": "Disguise",
            "name_english": "Disguise",
            "skillgroup": "Stealth",
            "skillgroup_english": "Stealth",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "INT",
            "displayattribute": "INT",
            "source": "SR5",
            "page": "133",
            "attributemod": "4",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "e1e080a8-fb20-489a-a60f-084d717f7417",
            "suid": "23c3320c-5010-4b2e-ac46-76f0a86af0b9",
            "name": "Diving",
            "name_english": "Diving",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "BOD",
            "displayattribute": "BOD",
            "source": "SR5",
            "page": "133",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "e230ca94-9d46-48c0-b90a-14e62fbf67b0",
            "suid": "2c8e5f20-e52d-4844-89e9-51b92dba47df",
            "name": "Electronic Warfare",
            "name_english": "Electronic Warfare",
            "skillgroup": "Cracking",
            "skillgroup_english": "Cracking",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "3",
            "ratingmax": "12",
            "specializedrating": "6",
            "total": "6",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "3",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "e48b197b-014f-48df-8441-231a3411fae5",
            "suid": "3f93335c-49d6-4904-a97e-4c942ab05b59",
            "name": "Escape Artist",
            "name_english": "Escape Artist",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "133",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "b1b21734-20b9-482f-a7e4-145d881e66df",
            "suid": "b20acd11-f102-40f3-a641-e3c420fbdb91",
            "name": "Etiquette",
            "name_english": "Etiquette",
            "skillgroup": "Influence",
            "skillgroup_english": "Influence",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "138",
            "attributemod": "2",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "0ef0b34e-a446-4898-ba1b-2629926a209c",
            "suid": "47cb1e8b-c285-4c54-9aaa-75305ad6dd4f",
            "name": "First Aid",
            "name_english": "First Aid",
            "skillgroup": "Biotech",
            "skillgroup_english": "Biotech",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "65bae27c-fe24-4c18-9b54-5d7d0ccec4df",
            "suid": "c9f52f97-a284-44a7-8af6-802dd3ed554f",
            "name": "Forgery",
            "name_english": "Forgery",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "8898bff0-3da4-4e3b-9a7d-4f504bd458e3",
            "suid": "f510ccc3-cf95-4461-b2f7-e966daaa5a91",
            "name": "Free-Fall",
            "name_english": "Free-Fall",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "BOD",
            "displayattribute": "BOD",
            "source": "SR5",
            "page": "133",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "3a0d4656-f8b6-4127-8aef-b862b44d930a",
            "suid": "58452cff-44ea-41c6-a554-28a869149b27",
            "name": "Gunnery",
            "name_english": "Gunnery",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Vehicle Active",
            "skillcategory_english": "Vehicle Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "146",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "f87afedf-36cf-40d3-8daa-65f96f5792ed",
            "suid": "a9fa961d-07e5-46da-8edc-403ae3e6cc75",
            "name": "Gymnastics",
            "name_english": "Gymnastics",
            "skillgroup": "Athletics",
            "skillgroup_english": "Athletics",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "133",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "23fa927f-1f1b-4b58-a18f-6d79cf028c23",
            "suid": "c2bb65f5-4a6b-49bf-9925-ef6434cb6929",
            "name": "Hacking",
            "name_english": "Hacking",
            "skillgroup": "Cracking",
            "skillgroup_english": "Cracking",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "145",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "a1ea4b69-2250-4869-91b0-360ab762b120",
            "suid": "41e184e0-7273-403a-9300-fa29a1707bf0",
            "name": "Hardware",
            "name_english": "Hardware",
            "skillgroup": "Electronics",
            "skillgroup_english": "Electronics",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "145",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "24d69f8c-a223-4072-9d13-4c33244b96c3",
            "suid": "64841e6e-9487-4b63-80a1-dcad6eb78179",
            "name": "Heavy Weapons",
            "name_english": "Heavy Weapons",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "132",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "afb74498-1c51-4d7d-a085-592448f36f7c",
            "suid": "e7e5a43f-9762-4863-86dc-3fd7799e53a2",
            "name": "Impersonation",
            "name_english": "Impersonation",
            "skillgroup": "Acting",
            "skillgroup_english": "Acting",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "138",
            "attributemod": "2",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "bacbd3e8-a732-4b29-a226-ac3055bf70f9",
            "suid": "935621c5-d384-42f2-a740-1fa349fa85a1",
            "name": "Industrial Mechanic",
            "name_english": "Industrial Mechanic",
            "skillgroup": "Engineering",
            "skillgroup_english": "Engineering",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "145",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "cd394e9d-67de-4ba2-a5e0-96b81ab294aa",
            "suid": "3b34b209-00be-42b8-b4ac-cc7dea08af8a",
            "name": "Instruction",
            "name_english": "Instruction",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "138",
            "attributemod": "2",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "1b1952d2-6511-4af5-8f85-64e582b313bd",
            "suid": "9de43fad-b365-4e73-bc06-91dd571b858a",
            "name": "Intimidation",
            "name_english": "Intimidation",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "139",
            "attributemod": "2",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "96f68cd7-e942-40e7-884c-c1857d87853e",
            "suid": "963a548d-c629-4a13-a3e3-31b085a42e20",
            "name": "Leadership",
            "name_english": "Leadership",
            "skillgroup": "Influence",
            "skillgroup_english": "Influence",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "139",
            "attributemod": "2",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "9295c4d2-9feb-4d5e-9e65-e37b8d2e0921",
            "suid": "09fbc992-9fad-4f2d-ab56-725bac943dc6",
            "name": "Locksmith",
            "name_english": "Locksmith",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "145",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "d4c3c977-d20f-47e4-a437-65d448d3c926",
            "suid": "64088b25-de37-4d71-8800-4a430fde08af",
            "name": "Longarms",
            "name_english": "Longarms",
            "skillgroup": "Firearms",
            "skillgroup_english": "Firearms",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "132",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "c1205595-5cc9-4d63-9443-9c9729ae76a8",
            "suid": "938be691-4b3d-49a2-a673-bbf9924ce8f0",
            "name": "Medicine",
            "name_english": "Medicine",
            "skillgroup": "Biotech",
            "skillgroup_english": "Biotech",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "145",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "53b42b91-c9f5-41ca-a256-366237db7df4",
            "suid": "48cc79be-f75e-4fe6-8721-7864c9f231f6",
            "name": "Nautical Mechanic",
            "name_english": "Nautical Mechanic",
            "skillgroup": "Engineering",
            "skillgroup_english": "Engineering",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "145",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "ce941a67-53f3-46ac-92e4-537e4383c9dd",
            "suid": "f8037e7f-d48b-452b-8f66-2e0c36677fea",
            "name": "Navigation",
            "name_english": "Navigation",
            "skillgroup": "Outdoors",
            "skillgroup_english": "Outdoors",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "INT",
            "displayattribute": "INT",
            "source": "SR5",
            "page": "145",
            "attributemod": "4",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "736d8550-5005-4f2a-91eb-67a8b019ae5f",
            "suid": "729c9cee-ef8f-492d-aa7f-17ec1bc3816e",
            "name": "Negotiation",
            "name_english": "Negotiation",
            "skillgroup": "Influence",
            "skillgroup_english": "Influence",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "139",
            "attributemod": "2",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "120ecf2b-dcbf-495b-b31b-cacc67fd078a",
            "suid": "17fbaafa-8dbb-4f29-9244-5ae1cd4ac42f",
            "name": "Palming",
            "name_english": "Palming",
            "skillgroup": "Stealth",
            "skillgroup_english": "Stealth",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "133",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "a7296a7d-1770-4a39-b4ed-46f6a91f1d95",
            "suid": "04e1eb3e-e82d-485b-a7fd-1e677df2a070",
            "name": "Perception",
            "name_english": "Perception",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "INT",
            "displayattribute": "INT",
            "source": "SR5",
            "page": "133",
            "attributemod": "4",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "aea72e0f-08f3-40f9-a369-5ca6af6cce1b",
            "suid": "53f96d6a-363b-4c14-be1d-68e74930c67b",
            "name": "Performance",
            "name_english": "Performance",
            "skillgroup": "Acting",
            "skillgroup_english": "Acting",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "139",
            "attributemod": "2",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "0cc0660b-b72a-4bd8-a22e-a7bd89c8a7b1",
            "suid": "3ba9397e-f790-44ca-ae40-15a2356e348d",
            "name": "Pilot Aerospace",
            "name_english": "Pilot Aerospace",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Vehicle Active",
            "skillcategory_english": "Vehicle Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "REA",
            "displayattribute": "REA",
            "source": "SR5",
            "page": "146",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "5e605f5b-628e-49be-9688-089dc91138e9",
            "suid": "10d5c887-a1e5-4cca-8613-3a28f1aab810",
            "name": "Pilot Aircraft",
            "name_english": "Pilot Aircraft",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Vehicle Active",
            "skillcategory_english": "Vehicle Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "REA",
            "displayattribute": "REA",
            "source": "SR5",
            "page": "147",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "3a42cd39-b066-4988-9629-40c3d2b79148",
            "suid": "ae91a8a6-80e7-4f52-b9eb-21725a5528a4",
            "name": "Pilot Ground Craft",
            "name_english": "Pilot Ground Craft",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Vehicle Active",
            "skillcategory_english": "Vehicle Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "REA",
            "displayattribute": "REA",
            "source": "SR5",
            "page": "147",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "57ff9662-a20a-4230-93d7-d8fd29d55bbb",
            "suid": "b8a24d87-465a-4365-9948-038fe1ac62c4",
            "name": "Pilot Walker",
            "name_english": "Pilot Walker",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Vehicle Active",
            "skillcategory_english": "Vehicle Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "REA",
            "displayattribute": "REA",
            "source": "SR5",
            "page": "147",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "f58dfb5a-360b-4bca-a68a-f24935c467f7",
            "suid": "1579818e-af85-47cd-8c9f-2e86e9dc19da",
            "name": "Pilot Watercraft",
            "name_english": "Pilot Watercraft",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Vehicle Active",
            "skillcategory_english": "Vehicle Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "REA",
            "displayattribute": "REA",
            "source": "SR5",
            "page": "147",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "40353da4-0e4d-43bb-91cd-f9e6e9cba9a9",
            "suid": "adf31a50-b228-4e09-a09c-46ab9f5e59a1",
            "name": "Pistols",
            "name_english": "Pistols",
            "skillgroup": "Firearms",
            "skillgroup_english": "Firearms",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "132",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "df1b2ed9-1244-4dba-8197-09d1c6ba345d",
            "suid": "9cff9aa7-d092-4f89-8b7b-3ab835818874",
            "name": "Sneaking",
            "name_english": "Sneaking",
            "skillgroup": "Stealth",
            "skillgroup_english": "Stealth",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "133",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "1429de2d-beda-409d-adc2-79ab50bdf482",
            "suid": "b693f3bf-48dc-4570-9743-d94d14ee698b",
            "name": "Software",
            "name_english": "Software",
            "skillgroup": "Electronics",
            "skillgroup_english": "Electronics",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "145",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "b7a3990e-9635-426b-87ee-db404bb4bcd6",
            "suid": "89ee1730-053a-400f-a13a-4fbadae015f0",
            "name": "Survival",
            "name_english": "Survival",
            "skillgroup": "Outdoors",
            "skillgroup_english": "Outdoors",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "WIL",
            "displayattribute": "WIL",
            "source": "SR5",
            "page": "133",
            "attributemod": "7",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "7c2ac898-78e8-40f2-94a8-66cfb8092246",
            "suid": "867a6fa0-7d98-4cde-83a4-b33dd39de08e",
            "name": "Throwing Weapons",
            "name_english": "Throwing Weapons",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "132",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "4b3f0102-afaa-4b50-a087-195258b95182",
            "suid": "7ed2f3e0-a791-4cb7-ba3e-ac785fdc3d7e",
            "name": "Tracking",
            "name_english": "Tracking",
            "skillgroup": "Outdoors",
            "skillgroup_english": "Outdoors",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "INT",
            "displayattribute": "INT",
            "source": "SR5",
            "page": "134",
            "attributemod": "4",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "7c2d4d6f-9183-4826-a5ef-ff537fa5fed2",
            "suid": "4fcd40cb-4b02-4b7e-afcb-f44d46cd5706",
            "name": "Unarmed Combat",
            "name_english": "Unarmed Combat",
            "skillgroup": "Close Combat",
            "skillgroup_english": "Close Combat",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "False",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "132",
            "attributemod": "0",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          }
        ]
      },
      "contacts": null,
      "limitmodifiersphys": null,
      "limitmodifiersment": null,
      "limitmodifierssoc": null,
      "mentorspirits": null,
      "spells": null,
      "powers": null,
      "spirits": null,
      "complexforms": null,
      "aiprograms": null,
      "martialarts": null,
      "armors": null,
      "weapons": {
        "weapon": {
          "guid": "6ec89e25-9421-4a78-b3a5-2c7f2f33ae36",
          "sourceid": "63dcfdb6-bbd9-4a58-bbf4-cd35f7614fdc",
          "name": "Unarmed Attack",
          "name_english": "Unarmed Attack",
          "fullname": "Unarmed Attack",
          "fullname_english": "Unarmed Attack",
          "category": "Unarmed",
          "category_english": "Unarmed",
          "type": "Melee",
          "reach": "0",
          "rawreach": "0",
          "accuracy": "0",
          "accuracy_noammo": "0",
          "accuracy_english": "0",
          "accuracy_english_noammo": "0",
          "rawaccuracy": "Physical",
          "damage": "0S",
          "damage_noammo": "0S",
          "damage_english": "0S",
          "damage_noammo_english": "0S",
          "rawdamage": "({STR})S",
          "ap": "-",
          "ap_noammo": "-",
          "ap_english": "-",
          "ap_english_noammo": "-",
          "rawap": "-",
          "mode": null,
          "mode_noammo": null,
          "mode_english": null,
          "mode_english_noammo": null,
          "rc": "1",
          "rc_noammo": "1",
          "rc_english": "1",
          "rc_english_noammo": "1",
          "rawrc": "0",
          "ammo": "0",
          "ammo_english": "0",
          "maxammo": "0",
          "conceal": "0",
          "rawconceal": "0",
          "availablemounts": "None",
          "availablemounts_english": "None",
          "avail": "0",
          "avail_english": "0",
          "cost": "0",
          "owncost": "0",
          "weight": "0",
          "ownweight": "0",
          "source": "SR5",
          "page": "132",
          "weaponname": null,
          "location": null,
          "attack": "0",
          "sleaze": "0",
          "dataprocessing": "2",
          "firewall": "2",
          "devicerating": "2",
          "programlimit": "0",
          "iscommlink": "False",
          "isprogram": "False",
          "active": "False",
          "homenode": "False",
          "conditionmonitor": "9",
          "matrixcmfilled": "0",
          "ranges": {
            "name": "Unarmed",
            "name_english": "Unarmed",
            "short": null,
            "medium": null,
            "long": null,
            "extreme": null
          },
          "alternateranges": {
            "name": null,
            "name_english": null,
            "short": null,
            "medium": null,
            "long": null,
            "extreme": null
          },
          "availableammo": "0",
          "currentammo": "None",
          "currentammo_english": "None",
          "clips": null,
          "dicepool": "0",
          "dicepool_noammo": "0",
          "skill": "Unarmed Combat",
          "wirelesson": "True"
        }
      },
      "cyberwares": null,
      "qualities": null,
      "lifestyles": null,
      "gears": null,
      "drugs": null,
      "vehicles": null,
      "initiationgrade": null,
      "metamagics": null,
      "arts": null,
      "enhancements": null,
      "critterpowers": {
        "critterpower": [
          {
            "guid": "bbfe3cbf-31d5-4b1f-8e36-c2c50f3b6b77",
            "sourceid": "765bf1cb-2e4b-46e8-aee4-f19004f031f3",
            "name": "Bodyguard",
            "fullname": "Bodyguard",
            "name_english": "Bodyguard",
            "fullname_english": "Bodyguard",
            "extra": null,
            "extra_english": null,
            "category": "Emergent",
            "category_english": "Emergent",
            "type": "None",
            "type_english": "None",
            "action": "None",
            "action_english": "None",
            "range": null,
            "range_english": null,
            "duration": null,
            "duration_english": null,
            "karma": "0",
            "source": "KC",
            "page": "100"
          },
          {
            "guid": "8b7dbcb1-7e8d-4e37-b3cd-524e8a80d930",
            "sourceid": "d8e72e33-d70e-4fd5-8ca2-b6cb7da87a96",
            "name": "Shield",
            "fullname": "Shield",
            "name_english": "Shield",
            "fullname_english": "Shield",
            "extra": null,
            "extra_english": null,
            "category": "Emergent",
            "category_english": "Emergent",
            "type": "None",
            "type_english": "None",
            "action": "None",
            "action_english": "None",
            "range": null,
            "range_english": null,
            "duration": null,
            "duration_english": null,
            "karma": "0",
            "source": "KC",
            "page": "100"
          }
        ]
      },
      "sustainedobjects": null,
      "otherarmors": null,
      "calendar": null
    }
  }
} as const satisfies ActorFile;