import { ActorFile } from "@/module/apps/actorImport/ActorSchema";

export const FireSpirit = {
  "?xml": {
    "@version": "1.0",
    "@encoding": "utf-8"
  },
  "characters": {
    "character": {
      "settings": "67e25032-2a4e-42ca-97fa-69f7f608236c",
      "buildmethod": "Priority",
      "imageformat": "jpeg",
      "metatype": "Spirit of Fire",
      "metatype_english": "Spirit of Fire",
      "metatype_guid": "3232c4f1-0b22-4799-8c80-392392f9af38",
      "metavariant": null,
      "metavariant_english": null,
      "metavariant_guid": "00000000-0000-0000-0000-000000000000",
      "movement": "10/20; 5m / hit, Swim: 6/12; 5m / hit, Fly: 10/20; 5m / hit",
      "walk": "10/20; 5m / hit, Swim: 6/12; 5m / hit, Fly: 10/20; 5m / hit",
      "run": "10/20; 5m / hit, Swim: 6/12; 5m / hit, Fly: 10/20; 5m / hit",
      "sprint": "10/20; 5m / hit, Swim: 6/12; 5m / hit, Fly: 10/20; 5m / hit",
      "movementwalk": "10/20; 5m / hit",
      "movementswim": "6/12; 5m / hit",
      "movementfly": "10/20; 5m / hit",
      "prioritymetatype": "A",
      "priorityattributes": "B",
      "priorityspecial": "C",
      "priorityskills": [
        "D",
        null
      ],
      "priorityresources": "E",
      "primaryarm": "Right",
      "name": "Unnamed Character",
      "gender": null,
      "age": null,
      "eyes": null,
      "height": null,
      "weight": null,
      "skin": null,
      "hair": null,
      "description": null,
      "background": null,
      "concept": null,
      "notes": null,
      "alias": null,
      "playername": null,
      "gamenotes": null,
      "limitphysical": "4",
      "limitmental": "5",
      "limitsocial": "4",
      "limitastral": "5",
      "contactpoints": "9",
      "contactpointsused": "0",
      "cfplimit": "0",
      "ainormalprogramlimit": "0",
      "aiadvancedprogramlimit": "0",
      "spelllimit": "0",
      "karma": "0",
      "totalkarma": "0",
      "special": "0",
      "totalspecial": "0",
      "attributes": [
        "0",
        {
          "attributecategory_english": "Standard",
          "attribute": [
            {
              "name_english": "STR",
              "name": "STR",
              "base": "1",
              "total": "1",
              "min": "1",
              "max": "1",
              "aug": "1",
              "bp": "0",
              "metatypecategory": "Standard"
            },
            {
              "name_english": "CHA",
              "name": "CHA",
              "base": "3",
              "total": "3",
              "min": "3",
              "max": "3",
              "aug": "3",
              "bp": "0",
              "metatypecategory": "Standard"
            },
            {
              "name_english": "INT",
              "name": "INT",
              "base": "4",
              "total": "4",
              "min": "4",
              "max": "4",
              "aug": "4",
              "bp": "0",
              "metatypecategory": "Standard"
            },
            {
              "name_english": "AGI",
              "name": "AGI",
              "base": "5",
              "total": "5",
              "min": "5",
              "max": "5",
              "aug": "5",
              "bp": "0",
              "metatypecategory": "Standard"
            },
            {
              "name_english": "REA",
              "name": "REA",
              "base": "6",
              "total": "6",
              "min": "6",
              "max": "6",
              "aug": "6",
              "bp": "0",
              "metatypecategory": "Standard"
            },
            {
              "name_english": "ESS",
              "name": "ESS",
              "base": "1",
              "total": "1",
              "min": "1",
              "max": "3",
              "aug": "3",
              "bp": "0",
              "metatypecategory": "Special"
            },
            {
              "name_english": "EDG",
              "name": "EDG",
              "base": "2",
              "total": "2",
              "min": "2",
              "max": "2",
              "aug": "2",
              "bp": "0",
              "metatypecategory": "Special"
            },
            {
              "name_english": "MAG",
              "name": "MAG",
              "base": "3",
              "total": "3",
              "min": "3",
              "max": "3",
              "aug": "3",
              "bp": "0",
              "metatypecategory": "Special"
            },
            {
              "name_english": "LOG",
              "name": "LOG",
              "base": "3",
              "total": "3",
              "min": "3",
              "max": "3",
              "aug": "3",
              "bp": "0",
              "metatypecategory": "Standard"
            },
            {
              "name_english": "BOD",
              "name": "BOD",
              "base": "4",
              "total": "4",
              "min": "4",
              "max": "4",
              "aug": "4",
              "bp": "0",
              "metatypecategory": "Standard"
            },
            {
              "name_english": "WIL",
              "name": "WIL",
              "base": "3",
              "total": "3",
              "min": "3",
              "max": "3",
              "aug": "3",
              "bp": "0",
              "metatypecategory": "Standard"
            }
          ]
        }
      ],
      "totalattributes": "0",
      "edgeused": "0",
      "edgeremaining": "2",
      "streetcred": "0",
      "calculatedstreetcred": "0",
      "totalstreetcred": "0",
      "burntstreetcred": "0",
      "notoriety": "0",
      "calculatednotoriety": "0",
      "totalnotoriety": "0",
      "publicawareness": "0",
      "calculatedpublicawareness": "0",
      "totalpublicawareness": "0",
      "astralreputation": "0",
      "totalastralreputation": "0",
      "wildreputation": "0",
      "totalwildreputation": "0",
      "created": "True",
      "nuyen": "0",
      "adept": "False",
      "magician": "False",
      "technomancer": "False",
      "ai": "False",
      "cyberwaredisabled": "False",
      "critter": "True",
      "totaless": "3.00",
      "dodge": "10",
      "armor": "0",
      "firearmor": "0",
      "coldarmor": "0",
      "electricityarmor": "0",
      "acidarmor": "0",
      "fallingarmor": "0",
      "armordicestun": "4",
      "firearmordicestun": "4",
      "coldarmordicestun": "4",
      "electricityarmordicestun": "4",
      "acidarmordicestun": "4",
      "fallingarmordicestun": "4",
      "armordicephysical": "4",
      "firearmordicephysical": "4",
      "coldarmordicephysical": "4",
      "electricityarmordicephysical": "4",
      "acidarmordicephysical": "4",
      "fallingarmordicephysical": "4",
      "physicalcm": "10",
      "physicalcmiscorecm": "False",
      "stuncm": "10",
      "stuncmismatrixcm": "False",
      "physicalcmfilled": "0",
      "stuncmfilled": "0",
      "cmthreshold": "3",
      "physicalcmthresholdoffset": "0",
      "stuncmthresholdoffset": "0",
      "cmoverflow": "5",
      "psyche": "False",
      "init": "10 + 2d6",
      "initdice": "2",
      "initvalue": "10",
      "initbonus": "0",
      "astralinit": "8 + 3d6",
      "astralinitdice": "3",
      "astralinitvalue": "8",
      "matrixarinit": "10 + 2d6",
      "matrixarinitdice": "2",
      "matrixarinitvalue": "10",
      "matrixcoldinit": "4 + DP + 3d6",
      "matrixcoldinitdice": "3",
      "matrixcoldinitvalue": "4",
      "matrixhotinit": "4 + DP + 4d6",
      "matrixhotinitdice": "4",
      "matrixhotinitvalue": "4",
      "riggerinit": "10 + 2d6",
      "magenabled": "True",
      "initiategrade": "0",
      "resenabled": "False",
      "submersiongrade": "0",
      "depenabled": "False",
      "groupmember": "False",
      "groupname": null,
      "groupnotes": null,
      "surprise": "10",
      "composure": "6",
      "judgeintentions": "7",
      "judgeintentionsresist": "6",
      "liftandcarry": "5",
      "memory": "6",
      "liftweight": "15",
      "carryweight": "10",
      "totalcarriedweight": "0",
      "fatigueresist": "7",
      "radiationresist": "7",
      "sonicresist": "3",
      "toxincontactresist": "7",
      "toxiningestionresist": "7",
      "toxininhalationresist": "7",
      "toxininjectionresist": "7",
      "pathogencontactresist": "7",
      "pathogeningestionresist": "7",
      "pathogeninhalationresist": "7",
      "pathogeninjectionresist": "7",
      "physiologicaladdictionresistfirsttime": "7",
      "physiologicaladdictionresistalreadyaddicted": "7",
      "psychologicaladdictionresistfirsttime": "6",
      "psychologicaladdictionresistalreadyaddicted": "6",
      "physicalcmnaturalrecovery": "8",
      "stuncmnaturalrecovery": "7",
      "indirectdefenseresist": "10",
      "directmanaresist": "3",
      "directphysicalresist": "4",
      "detectionspellresist": "6",
      "decreasebodresist": "7",
      "decreaseagiresist": "8",
      "decreaserearesist": "9",
      "decreasestrresist": "4",
      "decreasecharesist": "6",
      "decreaseintresist": "7",
      "decreaselogresist": "6",
      "decreasewilresist": "6",
      "illusionmanaresist": "6",
      "illusionphysicalresist": "7",
      "manipulationmentalresist": "6",
      "manipulationphysicalresist": "5",
      "skills": {
        "skill": [
          {
            "guid": "01b33008-04ff-464c-824f-1f23a3408672",
            "suid": "88ee65ba-c797-4f9c-91fe-39bc43b0f9c8",
            "name": "Exotic Ranged Weapon",
            "name_english": "Exotic Ranged Weapon",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "True",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": "Elemental Attack",
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "131",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "83c6d727-fb0f-46a3-bbfd-8c13d022e320",
            "suid": "b52f7575-eebf-41c4-938d-df3397b5ee68",
            "name": "Aeronautics Mechanic",
            "name_english": "Aeronautics Mechanic",
            "skillgroup": "Engineering",
            "skillgroup_english": "Engineering",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "143",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "c4897fc5-b779-47b6-a305-1afe5ba6a6d1",
            "suid": "e09e5aa7-e496-41a2-97ce-17f577361888",
            "name": "Animal Handling",
            "name_english": "Animal Handling",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "143",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "a01e0cf5-3210-43fd-b850-6f1dd668fe26",
            "suid": "74a68a9e-8c5b-4998-8dbb-08c1e768afc3",
            "name": "Arcana",
            "name_english": "Arcana",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Pseudo-Magical Active",
            "skillcategory_english": "Pseudo-Magical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "142",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "ff85312f-6bea-44de-b9d6-cd5a8722b2ff",
            "suid": "1537ca5c-fa93-4c05-b073-a2a0eed91b8e",
            "name": "Archery",
            "name_english": "Archery",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "130",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "00903ec6-3315-4d64-84d9-1e619c47da75",
            "suid": "ada6d9b2-e451-4289-be45-7085fa34a51a",
            "name": "Armorer",
            "name_english": "Armorer",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "143",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "bf4da39f-b1d1-49c1-b9e5-b9c49b934b5e",
            "suid": "2f4c706f-5ac5-4774-8a45-3b4667989a20",
            "name": "Artisan",
            "name_english": "Artisan",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "3",
            "total": "3",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "INT",
            "displayattribute": "INT",
            "source": "SR5",
            "page": "143",
            "attributemod": "4",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "2ee92ef3-6cca-4d55-8365-a71392d120e5",
            "suid": "788b387b-ee41-4e6a-bf22-481a8cc4cf9f",
            "name": "Automatics",
            "name_english": "Automatics",
            "skillgroup": "Firearms",
            "skillgroup_english": "Firearms",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "130",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "e99139c1-74db-4038-a9cd-a9aadbdac343",
            "suid": "5e5f2f7f-f63b-4f65-a65d-91b3d4523c6f",
            "name": "Automotive Mechanic",
            "name_english": "Automotive Mechanic",
            "skillgroup": "Engineering",
            "skillgroup_english": "Engineering",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "143",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "6fe0d698-99ff-40b5-b4bf-fca7075af17d",
            "suid": "ba624682-a5c0-4cf5-b47b-1021e6a1800d",
            "name": "Biotechnology",
            "name_english": "Biotechnology",
            "skillgroup": "Biotech",
            "skillgroup_english": "Biotech",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "e6b76d17-b514-4001-9798-dca8a6d08ca2",
            "suid": "48763fa5-4b89-48c7-80ff-d0a2761de4c0",
            "name": "Blades",
            "name_english": "Blades",
            "skillgroup": "Close Combat",
            "skillgroup_english": "Close Combat",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "130",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "bb7a5ebf-82e3-4bb5-969c-f76ea02e149c",
            "suid": "bd4d977a-cbd4-4289-99bb-896caed6786a",
            "name": "Chemistry",
            "name_english": "Chemistry",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "0908ad5c-05ca-4ce0-898d-777c58e4455d",
            "suid": "cd9f6bf7-fa48-464b-9a8f-c7ce26713a72",
            "name": "Clubs",
            "name_english": "Clubs",
            "skillgroup": "Close Combat",
            "skillgroup_english": "Close Combat",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "131",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "a6fabf14-5539-4678-8c37-29bfbff1327b",
            "suid": "1c14bf0d-cc69-4126-9a95-1f2429c11aa5",
            "name": "Computer",
            "name_english": "Computer",
            "skillgroup": "Electronics",
            "skillgroup_english": "Electronics",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "9900f2bc-c3e6-48da-9b41-80a78083da6c",
            "suid": "6d7f48d3-84a1-4fce-90d3-58d566f70fa6",
            "name": "Con",
            "name_english": "Con",
            "skillgroup": "Acting",
            "skillgroup_english": "Acting",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "138",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "3d409aa6-9a2f-47cf-96d7-b0f4f704ef26",
            "suid": "7143f979-aa48-4cc8-a29c-e010400e6e11",
            "name": "Cybercombat",
            "name_english": "Cybercombat",
            "skillgroup": "Cracking",
            "skillgroup_english": "Cracking",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "cb79979a-a41d-4668-90cb-d5cb15c45ee4",
            "suid": "9b386fe5-83b3-436f-9035-efd1c0f7a680",
            "name": "Cybertechnology",
            "name_english": "Cybertechnology",
            "skillgroup": "Biotech",
            "skillgroup_english": "Biotech",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "3ad75f14-c2ce-4036-8bb2-b9533a008bee",
            "suid": "276877e1-5cdf-4e95-befd-13c1abb5ae02",
            "name": "Demolitions",
            "name_english": "Demolitions",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "89cc8617-84f3-4bd1-8018-a9c41e586c1c",
            "suid": "9b2416b2-3e2b-4dd6-ab9d-530f493c1c22",
            "name": "Disguise",
            "name_english": "Disguise",
            "skillgroup": "Stealth",
            "skillgroup_english": "Stealth",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "3",
            "total": "3",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "INT",
            "displayattribute": "INT",
            "source": "SR5",
            "page": "133",
            "attributemod": "4",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "e33c7e43-bbf7-4b0e-b1c3-cd447d92ceb3",
            "suid": "23c3320c-5010-4b2e-ac46-76f0a86af0b9",
            "name": "Diving",
            "name_english": "Diving",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "3",
            "total": "3",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "BOD",
            "displayattribute": "BOD",
            "source": "SR5",
            "page": "133",
            "attributemod": "4",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "3d8f3874-461b-44cc-9a5b-5fb6d675eaa1",
            "suid": "2c8e5f20-e52d-4844-89e9-51b92dba47df",
            "name": "Electronic Warfare",
            "name_english": "Electronic Warfare",
            "skillgroup": "Cracking",
            "skillgroup_english": "Cracking",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "bcf574ad-ea59-4ec0-b3fb-9020b1d4b682",
            "suid": "3f93335c-49d6-4904-a97e-4c942ab05b59",
            "name": "Escape Artist",
            "name_english": "Escape Artist",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "133",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "6ee0a1ed-c2ac-420c-88f2-ff0f985e6eb7",
            "suid": "b20acd11-f102-40f3-a641-e3c420fbdb91",
            "name": "Etiquette",
            "name_english": "Etiquette",
            "skillgroup": "Influence",
            "skillgroup_english": "Influence",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "138",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "eda2441e-21fb-4020-bb15-7dbf8ad441de",
            "suid": "47cb1e8b-c285-4c54-9aaa-75305ad6dd4f",
            "name": "First Aid",
            "name_english": "First Aid",
            "skillgroup": "Biotech",
            "skillgroup_english": "Biotech",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "9f7862f0-063b-40b4-ae93-a1f3f191f5ab",
            "suid": "27db6e2a-a49f-4232-b150-e676b8dacb52",
            "name": "Flight",
            "name_english": "Flight",
            "skillgroup": "Athletics",
            "skillgroup_english": "Athletics",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "True",
            "rating": "3",
            "ratingmax": "12",
            "specializedrating": "8",
            "total": "8",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "3",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "394",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "3bdb7580-7c06-49ba-867b-cfaded5f816c",
            "suid": "c9f52f97-a284-44a7-8af6-802dd3ed554f",
            "name": "Forgery",
            "name_english": "Forgery",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "144",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "9917110b-fe1f-4a2d-af22-d1d7ab90acc1",
            "suid": "f510ccc3-cf95-4461-b2f7-e966daaa5a91",
            "name": "Free-Fall",
            "name_english": "Free-Fall",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "3",
            "total": "3",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "BOD",
            "displayattribute": "BOD",
            "source": "SR5",
            "page": "133",
            "attributemod": "4",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "4fd6ff5b-664b-4977-81a8-7ed0871ed8e1",
            "suid": "58452cff-44ea-41c6-a554-28a869149b27",
            "name": "Gunnery",
            "name_english": "Gunnery",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Vehicle Active",
            "skillcategory_english": "Vehicle Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "146",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "8d6bc5a4-5f6e-403c-a49e-1afba44e5658",
            "suid": "a9fa961d-07e5-46da-8edc-403ae3e6cc75",
            "name": "Gymnastics",
            "name_english": "Gymnastics",
            "skillgroup": "Athletics",
            "skillgroup_english": "Athletics",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "133",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "cd717770-01fa-4ba2-a513-1f8ce6bc4be3",
            "suid": "c2bb65f5-4a6b-49bf-9925-ef6434cb6929",
            "name": "Hacking",
            "name_english": "Hacking",
            "skillgroup": "Cracking",
            "skillgroup_english": "Cracking",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "145",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "72c93385-e2a2-4fa9-b516-ec81ad174ec3",
            "suid": "41e184e0-7273-403a-9300-fa29a1707bf0",
            "name": "Hardware",
            "name_english": "Hardware",
            "skillgroup": "Electronics",
            "skillgroup_english": "Electronics",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "145",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "ac6dadde-6973-4615-8384-264dbf314568",
            "suid": "64841e6e-9487-4b63-80a1-dcad6eb78179",
            "name": "Heavy Weapons",
            "name_english": "Heavy Weapons",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "132",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "718a6c6d-b1b8-4709-a043-cf0191489352",
            "suid": "e7e5a43f-9762-4863-86dc-3fd7799e53a2",
            "name": "Impersonation",
            "name_english": "Impersonation",
            "skillgroup": "Acting",
            "skillgroup_english": "Acting",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "138",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "6e8ff4b2-c5ae-40c8-ae65-d84d0da194d4",
            "suid": "935621c5-d384-42f2-a740-1fa349fa85a1",
            "name": "Industrial Mechanic",
            "name_english": "Industrial Mechanic",
            "skillgroup": "Engineering",
            "skillgroup_english": "Engineering",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "145",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "2659bba0-adaa-4d41-8a31-9b9de039d89a",
            "suid": "3b34b209-00be-42b8-b4ac-cc7dea08af8a",
            "name": "Instruction",
            "name_english": "Instruction",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "138",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "13b8d1f5-16bd-46f9-8336-f8fec8ad9751",
            "suid": "9de43fad-b365-4e73-bc06-91dd571b858a",
            "name": "Intimidation",
            "name_english": "Intimidation",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "139",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "961d3315-cdd6-42bc-b098-e46460fb8960",
            "suid": "963a548d-c629-4a13-a3e3-31b085a42e20",
            "name": "Leadership",
            "name_english": "Leadership",
            "skillgroup": "Influence",
            "skillgroup_english": "Influence",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "139",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "51eeab29-8695-4621-be29-a8b3ff5b6648",
            "suid": "09fbc992-9fad-4f2d-ab56-725bac943dc6",
            "name": "Locksmith",
            "name_english": "Locksmith",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "145",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "02375ff1-3a00-45f7-a837-8c635c1f76bc",
            "suid": "64088b25-de37-4d71-8800-4a430fde08af",
            "name": "Longarms",
            "name_english": "Longarms",
            "skillgroup": "Firearms",
            "skillgroup_english": "Firearms",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "132",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "dc1e0b03-6a7e-47fe-8d4a-12e6cf86eecb",
            "suid": "938be691-4b3d-49a2-a673-bbf9924ce8f0",
            "name": "Medicine",
            "name_english": "Medicine",
            "skillgroup": "Biotech",
            "skillgroup_english": "Biotech",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "145",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "b8eeac65-4dc5-4ad9-bbb4-29450b017df5",
            "suid": "48cc79be-f75e-4fe6-8721-7864c9f231f6",
            "name": "Nautical Mechanic",
            "name_english": "Nautical Mechanic",
            "skillgroup": "Engineering",
            "skillgroup_english": "Engineering",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "145",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "f96679a6-6f4b-4981-9d19-81d35f90d031",
            "suid": "f8037e7f-d48b-452b-8f66-2e0c36677fea",
            "name": "Navigation",
            "name_english": "Navigation",
            "skillgroup": "Outdoors",
            "skillgroup_english": "Outdoors",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "3",
            "total": "3",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "INT",
            "displayattribute": "INT",
            "source": "SR5",
            "page": "145",
            "attributemod": "4",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "eedaeff5-00b5-4761-9c7e-ad52fcd7409c",
            "suid": "729c9cee-ef8f-492d-aa7f-17ec1bc3816e",
            "name": "Negotiation",
            "name_english": "Negotiation",
            "skillgroup": "Influence",
            "skillgroup_english": "Influence",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "139",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "06eeaa23-bb7c-4c34-977b-b5c6b9c7a8eb",
            "suid": "17fbaafa-8dbb-4f29-9244-5ae1cd4ac42f",
            "name": "Palming",
            "name_english": "Palming",
            "skillgroup": "Stealth",
            "skillgroup_english": "Stealth",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "133",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "1c03b8be-46f9-4e04-9671-fb34aeb19c18",
            "suid": "04e1eb3e-e82d-485b-a7fd-1e677df2a070",
            "name": "Perception",
            "name_english": "Perception",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "3",
            "ratingmax": "12",
            "specializedrating": "7",
            "total": "7",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "3",
            "spec": null,
            "attribute": "INT",
            "displayattribute": "INT",
            "source": "SR5",
            "page": "133",
            "attributemod": "4",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "48b25d3c-ff0b-4f29-948b-774b8ec75118",
            "suid": "53f96d6a-363b-4c14-be1d-68e74930c67b",
            "name": "Performance",
            "name_english": "Performance",
            "skillgroup": "Acting",
            "skillgroup_english": "Acting",
            "skillcategory": "Social Active",
            "skillcategory_english": "Social Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "CHA",
            "displayattribute": "CHA",
            "source": "SR5",
            "page": "139",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "2eb1fcdc-5a1c-4da7-a92f-11d592c9918e",
            "suid": "3ba9397e-f790-44ca-ae40-15a2356e348d",
            "name": "Pilot Aerospace",
            "name_english": "Pilot Aerospace",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Vehicle Active",
            "skillcategory_english": "Vehicle Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "5",
            "total": "5",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "REA",
            "displayattribute": "REA",
            "source": "SR5",
            "page": "146",
            "attributemod": "6",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "f756eb36-3e7f-4645-89c6-5552b23aaeaf",
            "suid": "10d5c887-a1e5-4cca-8613-3a28f1aab810",
            "name": "Pilot Aircraft",
            "name_english": "Pilot Aircraft",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Vehicle Active",
            "skillcategory_english": "Vehicle Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "5",
            "total": "5",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "REA",
            "displayattribute": "REA",
            "source": "SR5",
            "page": "147",
            "attributemod": "6",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "a2971822-006e-4b62-bb0f-c8efeea32bc0",
            "suid": "ae91a8a6-80e7-4f52-b9eb-21725a5528a4",
            "name": "Pilot Ground Craft",
            "name_english": "Pilot Ground Craft",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Vehicle Active",
            "skillcategory_english": "Vehicle Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "5",
            "total": "5",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "REA",
            "displayattribute": "REA",
            "source": "SR5",
            "page": "147",
            "attributemod": "6",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "0647dcfd-4dad-42ce-85f9-af583ca1a2cd",
            "suid": "b8a24d87-465a-4365-9948-038fe1ac62c4",
            "name": "Pilot Walker",
            "name_english": "Pilot Walker",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Vehicle Active",
            "skillcategory_english": "Vehicle Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "5",
            "total": "5",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "REA",
            "displayattribute": "REA",
            "source": "SR5",
            "page": "147",
            "attributemod": "6",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "5f65edef-0b58-4804-a609-d91ad385df0c",
            "suid": "1579818e-af85-47cd-8c9f-2e86e9dc19da",
            "name": "Pilot Watercraft",
            "name_english": "Pilot Watercraft",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Vehicle Active",
            "skillcategory_english": "Vehicle Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "5",
            "total": "5",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "REA",
            "displayattribute": "REA",
            "source": "SR5",
            "page": "147",
            "attributemod": "6",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "64488156-e19b-43a6-96f2-c592c3663298",
            "suid": "adf31a50-b228-4e09-a09c-46ab9f5e59a1",
            "name": "Pistols",
            "name_english": "Pistols",
            "skillgroup": "Firearms",
            "skillgroup_english": "Firearms",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "132",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "dfeed27d-7cbc-4156-a1fd-cc521d000149",
            "suid": "1531b2d8-6116-4be4-87b0-232dba1fc447",
            "name": "Running",
            "name_english": "Running",
            "skillgroup": "Athletics",
            "skillgroup_english": "Athletics",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "True",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "STR",
            "displayattribute": "STR",
            "source": "SR5",
            "page": "133",
            "attributemod": "1",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "a6e26577-32bf-4837-8f9f-477a57e36ab9",
            "suid": "9cff9aa7-d092-4f89-8b7b-3ab835818874",
            "name": "Sneaking",
            "name_english": "Sneaking",
            "skillgroup": "Stealth",
            "skillgroup_english": "Stealth",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "133",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "a67f0042-75ef-478e-b175-d0a1f25a2291",
            "suid": "b693f3bf-48dc-4570-9743-d94d14ee698b",
            "name": "Software",
            "name_english": "Software",
            "skillgroup": "Electronics",
            "skillgroup_english": "Electronics",
            "skillcategory": "Technical Active",
            "skillcategory_english": "Technical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "LOG",
            "displayattribute": "LOG",
            "source": "SR5",
            "page": "145",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "9634d847-5abb-44e3-aaf9-3b255f856b45",
            "suid": "89ee1730-053a-400f-a13a-4fbadae015f0",
            "name": "Survival",
            "name_english": "Survival",
            "skillgroup": "Outdoors",
            "skillgroup_english": "Outdoors",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "2",
            "total": "2",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "WIL",
            "displayattribute": "WIL",
            "source": "SR5",
            "page": "133",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "997aae3e-4b23-4413-b2dd-125620a6ae9a",
            "suid": "0dbcb9cd-f824-4b5d-a387-90d33318b04c",
            "name": "Swimming",
            "name_english": "Swimming",
            "skillgroup": "Athletics",
            "skillgroup_english": "Athletics",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "True",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "0",
            "total": "0",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "STR",
            "displayattribute": "STR",
            "source": "SR5",
            "page": "134",
            "attributemod": "1",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "302bb213-7add-4997-b33b-f1fc5edbdd89",
            "suid": "867a6fa0-7d98-4cde-83a4-b33dd39de08e",
            "name": "Throwing Weapons",
            "name_english": "Throwing Weapons",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "4",
            "total": "4",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "132",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "9fe65362-88f4-4d18-97a8-5152cf3db023",
            "suid": "7ed2f3e0-a791-4cb7-ba3e-ac785fdc3d7e",
            "name": "Tracking",
            "name_english": "Tracking",
            "skillgroup": "Outdoors",
            "skillgroup_english": "Outdoors",
            "skillcategory": "Physical Active",
            "skillcategory_english": "Physical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "0",
            "ratingmax": "12",
            "specializedrating": "3",
            "total": "3",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "0",
            "spec": null,
            "attribute": "INT",
            "displayattribute": "INT",
            "source": "SR5",
            "page": "134",
            "attributemod": "4",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "c5269d14-91cc-4360-bdc2-4150b6132ae6",
            "suid": "4fcd40cb-4b02-4b7e-afcb-f44d46cd5706",
            "name": "Unarmed Combat",
            "name_english": "Unarmed Combat",
            "skillgroup": "Close Combat",
            "skillgroup_english": "Close Combat",
            "skillcategory": "Combat Active",
            "skillcategory_english": "Combat Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "3",
            "ratingmax": "12",
            "specializedrating": "8",
            "total": "8",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "3",
            "spec": null,
            "attribute": "AGI",
            "displayattribute": "AGI",
            "source": "SR5",
            "page": "132",
            "attributemod": "5",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "27f22e4d-9d12-458a-817a-fd131b6577eb",
            "suid": "b7599a42-ceed-4558-b357-865aa3e317f5",
            "name": "Astral Combat",
            "name_english": "Astral Combat",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Magical Active",
            "skillcategory_english": "Magical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "3",
            "ratingmax": "12",
            "specializedrating": "6",
            "total": "6",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "3",
            "spec": null,
            "attribute": "WIL",
            "displayattribute": "WIL",
            "source": "SR5",
            "page": "142",
            "attributemod": "3",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          },
          {
            "guid": "a1a664b5-e20c-4118-85bb-8e3509e95ad2",
            "suid": "59318078-e071-411b-9194-7222560e9f4a",
            "name": "Assensing",
            "name_english": "Assensing",
            "skillgroup": "None",
            "skillgroup_english": "None",
            "skillcategory": "Magical Active",
            "skillcategory_english": "Magical Active",
            "grouped": "False",
            "default": "True",
            "requiresgroundmovement": "False",
            "requiresswimmovement": "False",
            "requiresflymovement": "False",
            "rating": "3",
            "ratingmax": "12",
            "specializedrating": "7",
            "total": "7",
            "knowledge": "False",
            "exotic": "False",
            "buywithkarma": "False",
            "base": "0",
            "karma": "3",
            "spec": null,
            "attribute": "INT",
            "displayattribute": "INT",
            "source": "SR5",
            "page": "142",
            "attributemod": "4",
            "ratingmod": "0",
            "poolmod": "0",
            "islanguage": "False",
            "isnativelanguage": "False",
            "bp": "0",
            "skillspecializations": null
          }
        ]
      },
      "contacts": null,
      "limitmodifiersphys": null,
      "limitmodifiersment": null,
      "limitmodifierssoc": null,
      "mentorspirits": null,
      "spells": null,
      "powers": null,
      "spirits": null,
      "complexforms": null,
      "aiprograms": null,
      "martialarts": null,
      "armors": null,
      "weapons": {
        "weapon": {
          "guid": "6758e5fd-e273-4bf4-90be-bb013be323f5",
          "sourceid": "63dcfdb6-bbd9-4a58-bbf4-cd35f7614fdc",
          "name": "Unarmed Attack",
          "name_english": "Unarmed Attack",
          "fullname": "Unarmed Attack",
          "fullname_english": "Unarmed Attack",
          "category": "Unarmed",
          "category_english": "Unarmed",
          "type": "Melee",
          "reach": "0",
          "rawreach": "0",
          "accuracy": "4",
          "accuracy_noammo": "4",
          "accuracy_english": "4",
          "accuracy_english_noammo": "4",
          "rawaccuracy": "Physical",
          "damage": "1S",
          "damage_noammo": "1S",
          "damage_english": "1S",
          "damage_noammo_english": "1S",
          "rawdamage": "({STR})S",
          "ap": "-",
          "ap_noammo": "-",
          "ap_english": "-",
          "ap_english_noammo": "-",
          "rawap": "-",
          "mode": null,
          "mode_noammo": null,
          "mode_english": null,
          "mode_english_noammo": null,
          "rc": "2",
          "rc_noammo": "2",
          "rc_english": "2",
          "rc_english_noammo": "2",
          "rawrc": "0",
          "ammo": "0",
          "ammo_english": "0",
          "maxammo": "0",
          "conceal": "0",
          "rawconceal": "0",
          "availablemounts": "None",
          "availablemounts_english": "None",
          "avail": "0",
          "avail_english": "0",
          "cost": "0",
          "owncost": "0",
          "weight": "0",
          "ownweight": "0",
          "source": "SR5",
          "page": "132",
          "weaponname": null,
          "location": null,
          "attack": "0",
          "sleaze": "0",
          "dataprocessing": "2",
          "firewall": "2",
          "devicerating": "2",
          "programlimit": "0",
          "iscommlink": "False",
          "isprogram": "False",
          "active": "False",
          "homenode": "False",
          "conditionmonitor": "9",
          "matrixcmfilled": "0",
          "ranges": {
            "name": "Unarmed",
            "name_english": "Unarmed",
            "short": null,
            "medium": null,
            "long": null,
            "extreme": null
          },
          "alternateranges": {
            "name": null,
            "name_english": null,
            "short": null,
            "medium": null,
            "long": null,
            "extreme": null
          },
          "availableammo": "0",
          "currentammo": "None",
          "currentammo_english": "None",
          "clips": null,
          "dicepool": "8",
          "dicepool_noammo": "8",
          "skill": "Unarmed Combat",
          "wirelesson": "True"
        }
      },
      "cyberwares": null,
      "qualities": null,
      "lifestyles": null,
      "gears": null,
      "drugs": null,
      "vehicles": null,
      "initiationgrade": null,
      "metamagics": null,
      "arts": null,
      "enhancements": null,
      "critterpowers": {
        "critterpower": [
          {
            "guid": "682943a1-d0e9-47a6-96c6-a2a99b5214b0",
            "sourceid": "4f694634-7c91-4534-a9ff-7f8ae3002a1e",
            "name": "Search",
            "fullname": "Search",
            "name_english": "Search",
            "fullname_english": "Search",
            "extra": null,
            "extra_english": null,
            "category": "Paranormal",
            "category_english": "Paranormal",
            "type": "P",
            "type_english": "P",
            "action": "Complex",
            "action_english": "Complex",
            "range": "Special",
            "range_english": "Special",
            "duration": "Special",
            "duration_english": "Special",
            "karma": "0",
            "source": "SR5",
            "page": "400"
          },
          {
            "guid": "0e279bec-9b93-42df-a2b3-41420a386a0f",
            "sourceid": "99af5d63-9f6a-4a32-9bf6-9b8500a3c64c",
            "name": "Accident",
            "fullname": "Accident",
            "name_english": "Accident",
            "fullname_english": "Accident",
            "extra": null,
            "extra_english": null,
            "category": "Paranormal",
            "category_english": "Paranormal",
            "type": "P",
            "type_english": "P",
            "action": "Complex",
            "action_english": "Complex",
            "range": "LOS",
            "range_english": "LOS",
            "duration": "Instant",
            "duration_english": "Instant",
            "karma": "0",
            "source": "SR5",
            "page": "394"
          },
          {
            "guid": "24a11122-e9e6-4825-bd59-76979dcfdd1f",
            "sourceid": "0ea84be4-a293-44bf-bc60-52314495cc9a",
            "name": "Astral Form",
            "fullname": "Astral Form",
            "name_english": "Astral Form",
            "fullname_english": "Astral Form",
            "extra": null,
            "extra_english": null,
            "category": "Paranormal",
            "category_english": "Paranormal",
            "type": "M",
            "type_english": "M",
            "action": "Auto",
            "action_english": "Auto",
            "range": "Self",
            "range_english": "Self",
            "duration": "Always",
            "duration_english": "Always",
            "karma": "0",
            "source": "SR5",
            "page": "394"
          },
          {
            "guid": "04a4ea28-20aa-4081-9e2e-3f346a096043",
            "sourceid": "4517126f-6dcf-4c73-b7f5-cac77532c1f5",
            "name": "Confusion",
            "fullname": "Confusion",
            "name_english": "Confusion",
            "fullname_english": "Confusion",
            "extra": null,
            "extra_english": null,
            "category": "Paranormal",
            "category_english": "Paranormal",
            "type": "P",
            "type_english": "P",
            "action": "Complex",
            "action_english": "Complex",
            "range": "LOS",
            "range_english": "LOS",
            "duration": "S",
            "duration_english": "S",
            "karma": "0",
            "source": "SR5",
            "page": "395"
          },
          {
            "guid": "aa326b4b-6f8f-4c69-b8bd-507fcbe0f97a",
            "sourceid": "37e62625-1099-426f-94c9-2750aaa9902b",
            "name": "Elemental Attack",
            "fullname": "Elemental Attack (Fire)",
            "name_english": "Elemental Attack",
            "fullname_english": "Elemental Attack (Fire)",
            "extra": "Fire",
            "extra_english": "Fire",
            "category": "Paranormal",
            "category_english": "Paranormal",
            "type": "P",
            "type_english": "P",
            "action": "Complex",
            "action_english": "Complex",
            "range": "LOS",
            "range_english": "LOS",
            "duration": "Instant",
            "duration_english": "Instant",
            "karma": "0",
            "source": "SR5",
            "page": "396"
          },
          {
            "guid": "24c3f405-b0a3-4079-9848-18987d99760e",
            "sourceid": "37bc7c80-beb9-424d-a4b4-db8d3a31612c",
            "name": "Energy Aura",
            "fullname": "Energy Aura",
            "name_english": "Energy Aura",
            "fullname_english": "Energy Aura",
            "extra": null,
            "extra_english": null,
            "category": "Paranormal",
            "category_english": "Paranormal",
            "type": "P",
            "type_english": "P",
            "action": "Auto",
            "action_english": "Auto",
            "range": "Self",
            "range_english": "Self",
            "duration": "Always",
            "duration_english": "Always",
            "karma": "0",
            "source": "SR5",
            "page": "396"
          },
          {
            "guid": "111714da-dfab-4ff1-8c1c-780b9c249fd9",
            "sourceid": "f6fb5ceb-91f8-418b-99ee-413e8c16230e",
            "name": "Engulf",
            "fullname": "Engulf",
            "name_english": "Engulf",
            "fullname_english": "Engulf",
            "extra": null,
            "extra_english": null,
            "category": "Paranormal",
            "category_english": "Paranormal",
            "type": "P",
            "type_english": "P",
            "action": "Complex",
            "action_english": "Complex",
            "range": "T",
            "range_english": "T",
            "duration": "S",
            "duration_english": "S",
            "karma": "0",
            "source": "SR5",
            "page": "396"
          },
          {
            "guid": "fdfe069f-82c9-4b79-8c68-11f32279b352",
            "sourceid": "bf6c7543-0fa6-4297-8690-8230db5e46a8",
            "name": "Materialization",
            "fullname": "Materialization",
            "name_english": "Materialization",
            "fullname_english": "Materialization",
            "extra": null,
            "extra_english": null,
            "category": "Paranormal",
            "category_english": "Paranormal",
            "type": "P",
            "type_english": "P",
            "action": "Complex",
            "action_english": "Complex",
            "range": "Self",
            "range_english": "Self",
            "duration": "S",
            "duration_english": "S",
            "karma": "0",
            "source": "SR5",
            "page": "398"
          },
          {
            "guid": "e801197b-4ffe-409c-a174-fa9005d31213",
            "sourceid": "bd881fa0-89e4-4734-816f-7ffe7cf5f35f",
            "name": "Sapience",
            "fullname": "Sapience",
            "name_english": "Sapience",
            "fullname_english": "Sapience",
            "extra": null,
            "extra_english": null,
            "category": "Mundane",
            "category_english": "Mundane",
            "type": "P",
            "type_english": "P",
            "action": "Auto",
            "action_english": "Auto",
            "range": "Self",
            "range_english": "Self",
            "duration": "Always",
            "duration_english": "Always",
            "karma": "0",
            "source": "SR5",
            "page": "400"
          },
          {
            "guid": "2b3e3587-946c-477a-99f4-c4356878faeb",
            "sourceid": "67e02cc6-5099-473d-b185-3cd357af3e6f",
            "name": "Allergy",
            "fullname": "Allergy (Water, Severe)",
            "name_english": "Allergy",
            "fullname_english": "Allergy (Water, Severe)",
            "extra": "Water, Severe",
            "extra_english": "Water, Severe",
            "category": "Weakness",
            "category_english": "Weakness",
            "type": "None",
            "type_english": "None",
            "action": "None",
            "action_english": "None",
            "range": null,
            "range_english": null,
            "duration": null,
            "duration_english": null,
            "karma": "0",
            "source": "SR5",
            "page": "401"
          }
        ]
      },
      "sustainedobjects": null,
      "otherarmors": null,
      "calendar": null
    }
  }
} as const satisfies ActorFile;